### ISSUE TITLE
Eval clinique cardique: mise en forme tab

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1000]
il faudrait garder en blanc la tab sélectionnée (ici ECG) et en blanc shade, bleu clair celle qui est au over (ici : radio pulmonaire)

![capture d ecran 2015-06-08 a 16 33 22](https://cloud.githubusercontent.com/assets/1556490/8037132/569415c8-0dfc-11e5-9cd5-4aacd16b565b.png)

**Comment by maxencelaurent** [comment]
champagne !

**Comment by Rapou** [comment]
Style fixé + les images et styles sont externe au scénario
