### ISSUE TITLE
trainer - copie de jeu : manque retour UI

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1001]
si on va dans la modale et copie un jeu:
- on n'a pas de retour dans la modale que le jeu a été créé
- on referme la modale et le jeu n'est pas dans la liste: => il faut rafraichir la page

Proposition:
- retour dans la modale "game duplicated"
- faire en sorte que le jeu apparaisse sans avoir besoin de rafraichir la page

**Comment by Rapou** [comment]
Il n'y a pas d'option pour copier une session depuis le workspace trainer, c'était depuis le workspace scéanarist, ou hors Lobby ?

**Comment by djaccard** [comment]
oui, depuis workspace scénariste (je corrige le titre de l'issue)
