### ISSUE TITLE
trainer modale "players" 

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1003]
si on fait refresh, il y a le test player qui apparait
![capture d ecran 2015-06-29 a 19 21 41](https://cloud.githubusercontent.com/assets/1556490/8413890/29d94abe-1e94-11e5-81fa-58d855f92544.png)

**Comment by Rapou** [comment]
Fixed on b2a8828b36f6bb5c2a252ad4e6104f46b0e2f751
