### ISSUE TITLE
Stats mise en forme

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1004]
Est-ce qu'on pourrait mettre une largeur maximale aux rectangles de l'histogramme ? sinon, ça fait un peu lourd quand il n'y en a qu'un.
Ce serait bien si on pouvait par exemple avoir une largeur max. qui corresponde au cas où on a trois réponses, toujours partir à partir de la gauche. ça donnerait un peu de cohérence.

![capture d ecran 2015-07-03 a 09 07 51](https://cloud.githubusercontent.com/assets/1556490/8494242/63aa8b32-2163-11e5-964d-2f837ee4cabf.png)

On pourrait avoir quelque chose comme: 
![capture d ecran 2015-07-03 a 09 12 56](https://cloud.githubusercontent.com/assets/1556490/8494283/b81f382a-2163-11e5-98c2-57b2a7449ecb.png)

à partir de 4 réponses possibles, on commence à réduire la largeur des rectangles.

**Comment by CiGit** [comment]
Chartjs remplacé par Chartist
