### ISSUE TITLE
trainer: impact

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1007]
Excellent le côté "advanced impact" !

Pour les basic impacts, propositions design:
- pourquoi le champ texte mail est blanc à l'ouverture ? on devrait avoir tous les champs en grisés
- une fois qu'on a entré une valeur dans un champs, je trouve moyen ce texte en noir sur fond gris (pas si catastrophique). Mais est-ce qu'on pourrait essayer: à l'ouverture tous les champs grisés, champs où on a entré quelque chose ou qu'on est en train d'éditer passent en blanc. ça permettrait de rapidement voir où il y a quelque chose d'entré.
- mettre 3 lignes de plus au champs "body" du mail

![capture d ecran 2015-07-04 a 08 46 03](https://cloud.githubusercontent.com/assets/1556490/8506843/3dfd09c0-2229-11e5-912d-8fe9f8633395.png)

**Comment by Rapou** [comment]
Mauvaise issue fermée, concerne #1009
