### ISSUE TITLE
trainer : modale impact varie

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1008]
je ne sais pas comment reproduire, mais la modale est passé en mode où je ne vois plus tous les champs .

![capture d ecran 2015-07-04 a 08 51 51](https://cloud.githubusercontent.com/assets/1556490/8506858/2f7e4688-222a-11e5-8b03-af4354ec5910.png)

Plutôt que:
![capture d ecran 2015-07-04 a 08 46 03](https://cloud.githubusercontent.com/assets/1556490/8506860/4f118afa-222a-11e5-9c1e-7de77ead6a84.png)

Toujours laisser le 2è mode.

**Comment by Rapou** [comment]
Certainement un problème de cache qui gardait un ancien style. Corrigé dans fbffc589625afd0414b6fa12109b9b136c99d837 
Le display de la deuxième modale devrait être l'unique display à partir de maintenant.
