### ISSUE TITLE
tainer impact: validation

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1009]
actuellement quand on clique pour valider l'impact on arrive sur: 
![capture d ecran 2015-07-04 a 08 55 53](https://cloud.githubusercontent.com/assets/1556490/8506864/8cd49300-222a-11e5-8f76-b88a89d40aa8.png)

et il faut ensuite fermer la modale.

Est-ce qu'on pourrait avoir quelque chose de plus "jeu" et cohérent avec le reste de l'interface. Style une boite vert type "bouton submit" avec un vu (ou un vu dans un rond vert ou autre truc du style) qui apparait en fade au milieu de la modale (1/2 seconde), puis modale qui se referme en fade (rapidement).

**Comment by Rapou** [comment]
Corrigé dans  049ea73
