### ISSUE TITLE
notes trainer: éditeur html

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1011]
Est-ce qu'on pourrait ajouter la possibilité de mettre en forme les notes (surtout : gras, italique, liste à puces, éventuellement taille).

![capture d ecran 2015-07-04 a 09 03 34](https://cloud.githubusercontent.com/assets/1556490/8506908/d873db4e-222b-11e5-885b-fac24780267a.png)

**Comment by Rapou** [comment]
Fix with Dashboard review in 66b6144a806efb625370b600bbf7a1eec6c62aa5
