### ISSUE TITLE
accès aux jeux démos ne fonctionnent plus

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1014]
depuis site web, page acceuil: démo pmg (idem pour prog game)

![capture d ecran 2015-07-06 a 13 29 42](https://cloud.githubusercontent.com/assets/1556490/8521693/a5842470-23e6-11e5-87da-94aa84a04dac.png)

**Comment by Rapou** [comment]
Le PMG Démo fonctionne bien chez moi. Le proggame démo a une clé d'accès différente par contre, j'ai remis la clé normal à la place de proggame-demo-old. 

<img width="1047" alt="proggame" src="https://cloud.githubusercontent.com/assets/4618876/8522052/7c51fc4a-23ea-11e5-87ab-0bd0f10f99a5.png">

**Comment by Rapou** [comment]
Testé sous Chrome, Firefox, Safari, tout semble refonctionner

**Comment by djaccard** [comment]
ja'i restesté et ça fonctionne si on est déconnecté.
Si on est logué sur wegas, on reçoit ce message "error during joineng session".
Ce serait bien qu'il n'y ait pas de message d'erreur quand on rejoint un jeu démo et qu'on est déjà logué.
Il faudrait que ces jeux démos soient juste ouvert sans apparaître dans la liste des jeux du players, qu'il soit logué ou non.

**Comment by maxencelaurent** [comment]
En fait ça fonctionne si on est déjà connecté.
Le problème c'est lorsqu'on est déjà connecté ET qu'on a déjà rejoint la partie une fois. 

C'est comme si tu essaie d'utiliser deux fois la même clef d'accès sans avoir quitté la partie.

**Comment by maxencelaurent** [comment]
Ce qu'on peut imaginer comme solutions c'est :
1) Rouvrir la partie déjà existante
2) Lui proposer de redémarrer une nouvelle partie

**Comment by djaccard** [comment]
les deux solutions peuvent être ok pour moi. Si je reformule:
1) ouvrir un nouvel onglet avec la partie au même stade. Et c'est seulement si on ferme le nvaigateur et réouvre avant de cliquer sur le lien  pour la démo qu'on aura une nouvelle partie.
2) ouvrir un nouvel onglet avec une nouvelle partie à chaque clique sur "Demo" (ça remettrait à 0 aussi l'autre onglet)

**Comment by Rapou** [comment]
Il y avait bien un bug dans la logique. Normalement si on donnait l'url correspondant à une partie déjà rejointe, on devait être redirigé sur cette partie. Le bug est corrigé dans 4a8db45099a9037e1a0aad32d17bf7561c721629 

Pour n'importe quelle partie en accès "open" : les possibilités suivantes sont gérée : 

Partie individuelle : 
   - Joueur authentifié et n'as pas déjà rejoint la partie : Le joueur rejoint la partie et est redirigé sur le jeu,
   - Joueur authentifié et a déjà rejoint la partie : Le joueur est redirigé sur le jeu,
   - Pas d'authentification : L'utilisateur est connecté en "guest", rejoint la partie et est redirigé sur le jeu.

Partie en équipe : 
   - Joueur authentifié et n'as pas déjà rejoint la partie : Le joueur est redirigé sur l'interface pour rejoindre une équipe,
   - Joueur authentifié et a déjà rejoint la partie : Le joueur est redirigé sur le jeu,
   - Pas d'authentification : L'utilisateur est connecté en "guest", et est redirigé sur l'interface pour rejoindre une équipe.
