### ISSUE TITLE
player synchronisation

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1015]
une participante doit rafraichir la page pour voir les mises à jour (par exemple question répondue).
windows: IE 11, chrome: pas mis à jour sur les deux.
participante: dominique junod
team: team lady
session: 1396711

**Comment by maxencelaurent** [comment]
je pense que c'est idem que #1024 et #1021

**Comment by maxencelaurent** [comment]
OK avec dernière mise à jour OutdatedEntitiesEvent
