### ISSUE TITLE
impact team pas possible

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1017]
Je dois ajouter 6 à l'indicateur team de léquipe trust (session 1396711)
et j'ai le résultat Impact not applied, unexpected error null

![capture d ecran 2015-07-06 a 15 22 09](https://cloud.githubusercontent.com/assets/1556490/8522969/f57a4b06-23f2-11e5-9332-35ebb206ad19.png)

**Comment by djaccard** [comment]
j'ai rafraichi et fait l'impact en trois fois:
- +6 sur team
- -1 sur tima card
- envoi d'un mail 
Et ça a passé.
Je ne sais pas pourquoi j'ai eu cette erreur. Peut-être pas rempli un champ du mail ou autre erreur dans stress du cours et de tous les impacts à faire sur les différents groupes ?

**Comment by maxencelaurent** [comment]
Ok, pas facile à trouver la cause...
En fait, un joueur a quitter la partie alors que la page du trainer était déjà chargée, lorsque l'impact a été lancé, le player n'éxistant plus en DB -> BOUM

La solution -> mettre à jour en live avec websocket

**Comment by maxencelaurent** [comment]
sinon, un rechargement de la page règle le problème

**Comment by maxencelaurent** [comment]
branche "broadcastable" en cours
