### ISSUE TITLE
Sats: descendre au niveau du choice ?

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1018]
Dans quellle mesure est-ce que  ce serait possible de descnedre au niveau du choice plutôt que de s'arreter au result ?

ça donnerait par exemple:

Cost identification:
before goals identifaction 1*
after goals identification 2*
after tasks identification 1*

au lieu de Cost identification 4*

A discuter...

![capture d ecran 2015-07-06 a 17 45 53](https://cloud.githubusercontent.com/assets/1556490/8526448/1ad5d686-2407-11e5-94dd-fa9edc67224a.png)

![capture d ecran 2015-07-06 a 17 46 07](https://cloud.githubusercontent.com/assets/1556490/8526453/1fdbef62-2407-11e5-8cd6-b04780dff3c3.png)

**Comment by CiGit** [comment]
done in d66868648deda3507d88237df4e5a90816115dd4
