### ISSUE TITLE
laura.foti@unige.ch

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1020]
cette personne dit qu'elle n'a jamais créé de compte dans wegas et que lorsqu'elle a essayé de créer son compte, elle a reçu le message "mail déjà pris"
=> j'ai ragardé dans admin et effectivement, il y a un compte laura.foti@unige.ch.

Vous avez une idée autre que "elle est schizo" ?

j'ai essayé de lui modifier son mot de passe depuis l'admin, mais pas possible de sauver => elle va le faire par mail.

**Comment by maxencelaurent** [comment]
Ce compte a été créer ce matin à 8:51:49

**Comment by maxencelaurent** [comment]
duplicata #1019

**Comment by djaccard** [comment]
elle vient de partir chez le psy
