### ISSUE TITLE
Trainer-info partie : basé sur scénario

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1036]
Il faudrait mettre l'info " basé sur scéanrio pmg belleville" plus visible.

Par exemple dans la barre de titre, en sous-titre sour le nom de la partie: "Scénario: PMG-Belleville" (en petits caractères grisés). 
![capture d ecran 2015-08-20 a 08 51 49](https://cloud.githubusercontent.com/assets/1556490/9377421/2e8f21ac-4719-11e5-82cb-60839dfbd46f.png)

**Comment by Rapou** [comment]
Mauvaise issue fermée, Fix #1035
