### ISSUE TITLE
Problème affichage budget temps

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1063]
envoyer par Yves Delacrétaz:

Budget-temps : les carrés bleus ne s’affichent pas.
Windows/Chrome

![image001](https://cloud.githubusercontent.com/assets/1556490/9763870/1a26ff3e-570c-11e5-80d1-1eceb5eb93a3.png)

**Comment by maxencelaurent** [comment]
Est-ce que c'est encore possible avec la nouvelle version de l'affichage des cartes-temps ?

**Comment by git-jarle** [comment]
Dans quelles conditions est-ce que cela arrivait ? En tout cas le texte "Cartes temps" devrait toujours s'afficher. Je vois qu'il avait aussi un probl�me avec le "Unread count" sur les actions...

Le 3 janv. 2017 � 17:45, maxencelaurent <notifications@github.com<mailto:notifications@github.com>> a �crit :


Est-ce que c'est encore possible avec la nouvelle version de l'affichage des cartes-temps ?

-
