### ISSUE TITLE
créé par ...

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1065]
plutôt que créer par...
et pendant qu'on y est, en anglais: created by plutôt que create by

krèé dè, ichue sè. rigolo;

![capture d ecran 2015-09-11 a 11 02 05](https://cloud.githubusercontent.com/assets/1556490/9810973/9c5bc64c-5874-11e5-9c02-268a95cc1888.png)

**Comment by maxencelaurent** [comment]
la version a été créé**E** par ... !

**Comment by djaccard** [comment]
ta réson !
