### ISSUE TITLE
Admin: finaliser interfaces

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1069]
![capture d ecran 2015-09-18 a 13 07 23](https://cloud.githubusercontent.com/assets/1556490/9958079/44df179c-5e06-11e5-9001-59fb5c1918b2.png)

**Comment by djaccard** [comment]
Users
Mettre:
Nom Famille Prénom (username)
mail / no

**Comment by CiGit** [comment]
Encore:
* stats / partie -> ouvrir dans nouvelle fenêtre
* utilisateur : inverser action __be!__ / __edit__
* utilisateur : nom / prénom et tri par nom.
