### ISSUE TITLE
admin partie: bin/delete

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1070]
Est-ce qu'on pourrait mettre les 3 états:
- live
- archived
- deleted
![capture d ecran 2015-09-23 a 12 22 54](https://cloud.githubusercontent.com/assets/1556490/10043080/6d3d2754-61f0-11e5-8d79-9bcf38c6aed1.png)

**Comment by CiGit** [comment]
Il y a actuellement 4 états : 
``LIVE`` : partie standard
``BIN`` : "archive"
``DELETE`` : marquée pour suppression, mais pas réellement supprimée encore
``SUPPRESSED`` : n'existe plus sur le système.

**Comment by djaccard** [comment]
ah, alors on peut juste remplacer BIN par Archived comme ça on est cohérent avec l'interface.
