### ISSUE TITLE
Player rejoint équipe sans être passé par le login Wegas

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1072]
Deux personnes disent qu'elles ont fait:
- www.albasim.ch
- cliqué sur login / accès wegas
et qu'elles sont arrivées directement dans le workspace player. Elles ont ensuite entré la clé et rejoint l'équipe.
Elles disent qu'elles n'ont jamais accédé à wegas avant et qu'elles n'ont pas vu la page de login/create account. Elle ne se sont donc pas créé de compte. En allant dans le workspace, leur profil est effectivement vide.

Dans le trainer, je les vois comme guest.
![capture d ecran 2015-09-24 a 16 07 24](https://cloud.githubusercontent.com/assets/1556490/10075556/ad1c7640-62d6-11e5-9616-117ae77be6a6.png)

**Comment by djaccard** [comment]
En fait, on dirait qu'ils ont testé le PM-Game démo. ça les a logué en guest => problème qui en découle...

**Comment by maxencelaurent** [comment]
#1042

**Comment by CiGit** [comment]
WIP : eaa497af3c8bf3a90a8ecc92450c692f5b7ec7be

**Comment by CiGit** [comment]
Fixed by #1107
