### ISSUE TITLE
Bouton Next Phase: pas synchronisé avec trainer

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1077]
J'ai libéré la phase de réalisation (équipes bloquée en planif => réalisation ouverte jusqu'à dernière période)
Il y a des équipes qui ont dit que le bouton pas actif => en rafraichissant la page: ok.

Est-ce que le bouton n'est pas synchronisé ? est-ce que la limite pusher a été atteinte ?

**Comment by maxencelaurent** [comment]
C'est en principe synchronisé. Je ne vois pas de problème non plus avec la limite de pusher (on l'a uniquement approchée, pas atteinte)

**Comment by djaccard** [comment]
pas de reproduction pour le moment
