### ISSUE TITLE
Réservation ressources : décalage

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1080]
Mode réservation automatique

Yvonne a attrapé le rhume des foins => pas disponible
=> toutes les ressources du métier ont été décalée d'une période.

On a pu s'en sortir en mettant tout le monde en ASAP.

![capture d ecran 2015-09-26 a 14 37 56](https://cloud.githubusercontent.com/assets/1556490/10117606/6d54e37a-645d-11e5-8710-acd11b60ecb8.png)

**Comment by maxencelaurent** [comment]
OK, c'est pas lier au rhume d'Yvonne
