### ISSUE TITLE
PMG: add to task requirement

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1082]
Pour la réponse 3, il y a le métier informaticien logiciel qui a disparu.
Ce n'est pas le cas pour la réponse 2 ...
J'ai fait une copie de la version, puis corrigé.
Il faudrait voir de quoi c'est venu, sîl y a d'autres endroit où on a ceci.

![capture d ecran 2015-09-26 a 15 28 54](https://cloud.githubusercontent.com/assets/1556490/10117782/77b8833e-6463-11e5-9373-8ec5ddf31678.png)

**Comment by CiGit** [comment]
Le script enregistré:
```javascript
Variable.find(gameModel, "ProgrammationTraitements").addNumberAtInstanceProperty(self, "fixedCosts", "13000");
Variable.find(gameModel, "ProgrammationTraitements").addNumberAtInstanceProperty(self, "quality", "-12");
Variable.find(gameModel, "ProgrammationTraitements").addNumberAtInstanceProperty(self, "duration", "-1");
Variable.find(gameModel, "timeCards").add(self, -3);
Variable.find(gameModel, "ProgrammationTraitements").addAtRequirementVariable(self, 528449, "quantity", "-1");
Variable.find(gameModel, "ProgrammationTraitements").addAtRequirementVariable(self, 528450, "quantity", "-1");
```

Vraisemblablement le référencement par **ID** de la fonction `addAtRequirementVariable`

Egalement présent dans d'autres *GameModel*. **(9055)**

**Comment by maxencelaurent** [comment]
OK C'est corrigé
