### ISSUE TITLE
Finaliser les icones du scénariste

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1086]
Variables number
Trigger
Autres ? profiter de faire le tour.

**Comment by maxencelaurent** [comment]
ok

**Comment by djaccard** [comment]
mettre les icônes en grisé plutôt que noir ?

l'icône "nombre", avec le x2, fait un peu peur à tout ceux qui ont des mauvais souvenir des cours d'algèbre (par ex. quand j'ai montré l'éditeur à la RTS). Mais je ne sais pas par quoi remplacer: un digit (si jamais on demande à Sandrine de le créer ?) un N (bien que ce ne soit pas un naturel) ?
