### ISSUE TITLE
scéanriste : déplacement pages

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1095]
souvent, j'arrive à remonter une page dans l'arborescence, mais pas à la descendre.
![capture d ecran 2015-10-08 a 13 22 34](https://cloud.githubusercontent.com/assets/1556490/10364927/aba6088c-6dbf-11e5-937d-47cc301a2d78.png)

**Comment by CiGit** [comment]
J'imagine que c'est plutôt une question de "chance". De mon expérience avec, il fonctionne 1 fois sur 2. C'est à dire que s'il ne fonctionne pas, lacher et recommencer.
