### ISSUE TITLE
Dossiers "pages"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1097]
ce serait super pratique de pouvoir créer des dossiers pour regrouper les pages, par exemple:
- journaliste
- son image
- archives
  etc.
  ![capture d ecran 2015-10-08 a 13 34 36](https://cloud.githubusercontent.com/assets/1556490/10365227/139e2102-6dc2-11e5-8b29-bde89be2168b.png)

**Comment by djaccard** [comment]
demande de refaire toute la structure des pages

**Comment by IamFonky** [comment]
Corrigé par #1542
