### ISSUE TITLE
Mettre trainer en copie lors de l'envoi de vrai mails

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1104]
Suite au mail/problème d'Annick qui ne savait plus ce qu'elle avait envoyé.
copie au trainer soit automatiquement, soit une case à cocher (je pencherais pour la case à cocher).
Sinon possibilité de voir l'historique des mails envoyé dans wegas ?
à discuter...

**Comment by maxencelaurent** [comment]
Super chiant pour intégrer un historique

La version "copie automatique" me plait plus, car elle permet de contourner un problème potentielle de détection des ces mails en spam (actuellement, on envoie depuis l'adresse nobody@albasim.ch et on met replyTo: "le.mail@du.formateur", ce qui est parfois considérer comme une tricherie pour faire du spam)

En mettant automatiquement le formateur en CC, ça fera que les destinataires pouront lui répondre en faisant "reply to all"

Je mets ça en ligne pour le moment et on verra plus tard si on rajoute la case à cocher
