### ISSUE TITLE
Bouton + pour ajouter réponses

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1108]
Cool à l'utilisation ce bouton "+" pour les dossiers.
On pourrait le mettre pour ajouter une réponse à une questions ?
![capture d ecran 2015-10-27 a 07 42 41](https://cloud.githubusercontent.com/assets/1556490/10751220/8ba542e6-7c7e-11e5-9f26-1ace383bb234.png)

**Comment by maxencelaurent** [comment]
pas facile à savoir quoi ajouter lors du clic (ChoiceDescriptor ou SingleResultChoiceDescriptor)
