### ISSUE TITLE
Ajout trainer: fonctionne, mais on ne voit plus

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1110]
on ne voit plus les trainers ajoutés
Je viens s'ajouter pour test stefano mastrogiacomo
=> je n'arrive plus l'enlever...

![capture d ecran 2015-10-29 a 18 58 31](https://cloud.githubusercontent.com/assets/1556490/10827436/41fe3de4-7e6f-11e5-9383-e93c44228ffe.png)

**Comment by maxencelaurent** [comment]
#1105
