### ISSUE TITLE
IE: on ne voit pas le menu login se dérouler

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1115]
Depuis la page accueil albasim: clique sur "login" => il ne se passe rien, il n'y a pas "accès wegas, accès PMG"
Passé sur chorme => ok

Solution:
est-ce qu'on passe bientôt à :+1: clic sur login => directement page de connexion (plus le choix accès PMG/Wegas) et on envoie un mail aux profs ancienne version => accès direct par ...

**Comment by CiGit** [comment]
Version d'IE ? parce que j'ai aucun soucis avec le 11 / 10 / 9. Le 8 ne fonctionne pas (du tout)

**Comment by git-jarle** [comment]
Le menu login n'existe plus depuis longtemps.
