### ISSUE TITLE
Partie démo => problème connexion

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1117]
On a de novueau eu des étudiants qui n'ont pas compris ce qu'il se passait. Ils se sont connecté sur la démo, puis en faisant accès wegas, ils étaient directement connectés, avec le jeu démo dans leur liste, mais sans les champs à saisir pour créer le compte.
Ils disaient "mais pourquoi j'ai déjà ce jeu dans ma liste". je leur ai dit "c'est le jeu auquel vous aviez accédé en démo". Ils n'ont pas vu le sens...
Effectivement, en essaynt d'accéder à la démo, puis de me loguer, j'ai toujours comme avant. Est-ce que la correction a été mise en ligne ?

![capture d ecran 2015-11-03 a 15 40 37](https://cloud.githubusercontent.com/assets/1556490/10910734/6328ee12-8241-11e5-82c9-712d9df237a1.png)

**Comment by CiGit** [comment]
>  Est-ce que la correction a été mise en ligne ?

Non

**Comment by CiGit** [comment]
Fixed by #1107
