### ISSUE TITLE
scénariste: feedback sur search "full"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1120]
Actuellement, on n'a pas de retour utilisateur pendant le temps de la recherche.
Est-ce qu'on pourrait mettre quelque chose comme un truc qui tourne sur le bouton sur le boutn "full" ?
![capture d ecran 2015-11-04 a 08 42 52](https://cloud.githubusercontent.com/assets/1556490/10932335/3a4bf536-82d0-11e5-92e3-c5c73d2486c7.png)

**Comment by CiGit** [comment]
Bonne remarque
