### ISSUE TITLE
PMG : Changement de phase appliqué aux joueurs ?

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1121]
Depuis le trainer, j'ai libéré l'avancement (bloqué à fin initiation =>  bloqué fin planification).
Plusieurs groupes m'ont dit que lorsqu'ils se sont logués, ils étaient en phase de planification, sans avoir cliqué sur le bouton d'avancement de phase.
ça a posé le problème que certain n'avait pas tout à fait terminé l'avant-projet,
C'est possible ?

**Comment by CiGit** [comment]
Non

**Comment by maxencelaurent** [comment]
la seul manière de passé à une période ou une phase suivante est de cliquer sur le bouton.

Modifier la limite d'avancement va seulement dégrisé ce bouton

**Comment by djaccard** [comment]
c'est ce que j'ai toujours pensé... 
Après avoir torturé chaque les groupes, il y a à chaque fois eu un qui s'est dénoncé avoir cliqué sur le bouton next phase. sauf pour un groupe d'irréductibles.
=> on va mettre en non reproductible
