### ISSUE TITLE
PC--Frirefox : pas possible rejoindre un jeu/équipe

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1122]
On ne voit pas les équipes apparaitre.
Mise en page du lobby très bizarre.

![capture d ecran 2015-11-04 a 14 25 24](https://cloud.githubusercontent.com/assets/1556490/10939173/00dc9eba-8300-11e5-8575-7124fa9728b8.png)

![capture d ecran 2015-11-04 a 14 25 37](https://cloud.githubusercontent.com/assets/1556490/10939172/fc29cf50-82ff-11e5-8683-54d6dbe96f5f.png)

**Comment by maxencelaurent** [comment]
quelle version de firefox ?

**Comment by maxencelaurent** [comment]
chez moi (41.0.2), aucun problème à signaler
