### ISSUE TITLE
Trigger : mise en page

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1124]
Est-ce qu'on met: active by defaut/disable itself/only once en haut de la liste (entre name et conditions).
ça me parrait mieux qu'après conditions et impacts

![capture d ecran 2015-11-04 a 15 38 55](https://cloud.githubusercontent.com/assets/1556490/10941144/5a099844-830a-11e5-989c-8cbc35b43e28.png)

**Comment by JarleHulaas** [comment]
A ce sujet, j'ai trouvé le terme "active by default" un peu flou: s'agirait-il d'une sorte d'option?  Il me semble qu'il faudrait insister sur le fait que l'élément (trigger, question, ou autre) est actif dès le démarrage du jeu, par opposition au cas où il faut l'activer plus tard par un impact => "Active from start" ?
