### ISSUE TITLE
Newcity: Cohérence graphique EVM et Gantt

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1126]
Partie mas santé 15, équipe Newcity:
Graphique EVM va jusqu'en période 14
Gantt: se termine en période 8

Je ne sais pas non plus comment ils ont pu passer en clôture. Dans le dashboard trainer, ils sont bloqués en fin de réalisation. Les autres groupes n'ont pas pu passer en clôture....

**Comment by maxencelaurent** [comment]
on dirait qu'il y a une erreur dans la condition qui ouvre le passage en fin de projet...
je regarde ça entre ce soir et demain

**Comment by maxencelaurent** [comment]
résolution pour le passage en cloture bientot en ligne
