### ISSUE TITLE
PMG trainer: details

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1128]
Je n'arrive pas ouvrir les details du team
Il ne se passe rien quand je clique 
(Chrome / Firefox)
![capture d ecran 2015-11-16 a 14 31 39](https://cloud.githubusercontent.com/assets/1556490/11182936/020a7e9c-8c6f-11e5-846a-ba18a948ce93.png)

**Comment by CiGit** [comment]
C'est déjà corrigé, pas encore en ligne. 399c6d5c60182f875d1e0142e63261ad4ba6f857

**Comment by CiGit** [comment]
En ligne
