### ISSUE TITLE
Perte BAC

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1129]
L'équipe CMP 30 dit qu'elle a entré les BAC en planif et qu'ils ont disparu en réalisation. Ils sont assez sûr de les avoir entré (comme ils ont dû refaire la planif à cause du bug de retour en avant-projet, ils viennent de le faire et un membre du groupe à dicté les BAC à l'autre qui les a entré.)

**Comment by maxencelaurent** [comment]
le bug de retour en avant-projet ? Qu'est-ce que c'est ?

**Comment by maxencelaurent** [comment]
quelle partie ?

**Comment by maxencelaurent** [comment]
Probablement une coupure du réseau... Je vais verifier s'il manque pas des feedback en cas d'erreur...
