### ISSUE TITLE
Question "toogle": on ne devrait pas pouvoir valider si rien de choisi

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1138]
![capture d ecran 2015-11-26 a 07 59 51](https://cloud.githubusercontent.com/assets/1556490/11417071/d477fe9e-9413-11e5-9f51-6b4965432281.png)

**Comment by JarleHulaas** [comment]
Solved #1138 via https://github.com/Heigvd/Wegas/commit/0df1d16abbcedd9d18822a800d033510a67f1d2a
