### ISSUE TITLE
QCM standard: enlever "nombre de fois" à côté du titre question

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1139]
Pas de sens à dire qu'on a cocher deux cases.
![capture d ecran 2015-11-26 a 08 02 30](https://cloud.githubusercontent.com/assets/1556490/11417119/2d98a9ba-9414-11e5-9411-5c4ddd88d143.png)

**Comment by JarleHulaas** [comment]
Closed #1139 via https://github.com/Heigvd/Wegas/commit/0df1d16abbcedd9d18822a800d033510a67f1d2a
