### ISSUE TITLE
Questions: non effectué, non répondu

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1140]
Est-ce qu'on ne devrait pour toujours mettre "non effectué" ?

La différence avait un sens dans le PM-Game, mais pour les nouvelles simulations, ça crée plutôt une confusion en montrant une différence où il ne devrait pas y en avoir.

![capture d ecran 2015-11-26 a 08 03 55](https://cloud.githubusercontent.com/assets/1556490/11417147/79e1fbbe-9414-11e5-8ec5-5d3f440102fc.png)

**Comment by CiGit** [comment]
plus simple: on ne met rien . gras suffisant.

**Comment by JarleHulaas** [comment]
Solved #1140 via https://github.com/Heigvd/Wegas/commit/0df1d16abbcedd9d18822a800d033510a67f1d2a
