### ISSUE TITLE
QCM standard: en gras / pas en gras

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1141]
La question passe de gras à non gras lorsqu'on coche une case.

Il me semble que le changement devrait s'effectuer lorsqu'on clique sur submit. En même temps que le changement de "non effectué" à "effectué"

![capture d ecran 2015-11-26 a 08 07 22](https://cloud.githubusercontent.com/assets/1556490/11417182/e22118f4-9414-11e5-80bd-69f1debd76e7.png)

**Comment by JarleHulaas** [comment]
Solved #1141 via https://github.com/Heigvd/Wegas/commit/0df1d16abbcedd9d18822a800d033510a67f1d2a
