### ISSUE TITLE
Questions: plusieurs réponses possibles, mais max une fois pour chaque réponse

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1142]
Actuellement, on a les variantes:
- 1 réponse parmi n, 1 seule fois cette réponse
- allow multiple choices => n réponses possibles, possible de faire plusieurs fois chaque réponse

Est-ce qu'il serait possible d'avoir:
- plusieurs réponses possibles, mais une seule fois chaque réponse => une fois soumise, passe en grisé, mais les autres réponses sont aussi possibles.

ça ressemble au QCM standard de Jarle. Mais la différence c'est que ça permettrait de donner des résultats intermédiaire, laisserait la possibilité de soumettre une réponse, passer à autre chose, soumettre une autre réponse.

**Comment by CiGit** [comment]
=> 1 - illimité pour nbre réponse à question, idem pour nobre fois chque réponse

**Comment by CiGit** [comment]
# Options
Max question answer **#Q** [1,∞[
Max individual choice answer **#C** [1,∞[
~~Allow multiple replies~~ 

## Internal limits
**#Q** unsigned byte [1,255] U 0 as ∞
**#C** unsigned byte [1,255] U 0 as ∞

lack of support for *unsigned* in PSQL / Java
 - byte [-128, 127]
 - short (16-bit) [-32768, 32767]

Which size would make sens for **#Q #C**?
Allow **0** ?

# Transformation: Now to Next
```
Allow multiple replies ->
     #Q = ∞
     #C = ∞
Single reply ->
    #Q = 1
    #C = ∞
```
## Default values
**#Q** = 1
**#C** = 1
## Implementation impact
- QuestionDescriptor.java
- QuestionFacade.java
- QuestionSingleton.java

# Editor interface
In QuestionDescriptor's edition
```
Maximum allowed replies      number_input [ ]Unlimited
Maximum replies per choice   number_input [ ]Unlimited
```
## Implementation
inputex module for number input or Unlimited
could be a more generic input for *type* or checkbox, i.e. something or `null`
