### ISSUE TITLE
Viewer: mettre en évidence

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1143]
Souvent, on ne voit pas que quelqu'un a rejoint ou qu'un message est envoyé.

Est-ce qu'on pourrait avoir un truc style première lettre du prénom ? et voir la liste (ou au moins les 5 premiers) de ceux qui sont actuellement sur le scéanrio ?

Faire une mini animation lorsqu'on message est envoyé ? ou pastille type mail reçus ?

![capture d ecran 2015-11-29 a 11 34 16](https://cloud.githubusercontent.com/assets/1556490/11456572/61dc0110-968d-11e5-9da5-c5f064bd2573.png)

**Comment by CiGit** [comment]
Lorsque un message arrive, les petites bulles changent de couleur
![image](https://cloud.githubusercontent.com/assets/1453420/11468570/f32dd6fc-9750-11e5-856c-707fb7984baf.png)
Ce n'est vraisemblablement pas suffisant

**Comment by djaccard** [comment]
Non, on a vu que ce n'était pas suffisant.
