### ISSUE TITLE
Pastille info PF

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1144]
Comment est-ce qu'elle disparait ? On ne voit pas où il faut cliquer.
Il faudrait un truc qui permette au joueur de faire une action qui passe en "lu". ça serait mieux pour le joueur et pour le scénariste.

![capture d ecran 2015-11-29 a 11 38 38](https://cloud.githubusercontent.com/assets/1556490/11456585/1e1c8a8e-968e-11e5-9607-941b0f4d82aa.png)

**Comment by JarleHulaas** [comment]
Résolu à l'aide de inboxes dont les pastilles "unread" se mettent automatiquement à jour.
