### ISSUE TITLE
Workspace scénariste: partage scénario, ajouter username

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1145]
Sinon, ça fait bizarre: on cherche avec un user name et on a affiché quelque chose où on ne voit pas ce user name.

On pourrait mettre quelque chose comme : Dominique Jaccard (domscen) - djacc***@gmail.com

![capture d ecran 2015-11-30 a 05 02 42](https://cloud.githubusercontent.com/assets/1556490/11463269/a625e0c4-971f-11e5-9852-c0f0489ff9ee.png)

**Comment by CiGit** [comment]
Est-ce que tu dois vraiment pouvoir rechercher par *username* ? C'est le login d'une personne. Tout comme l'email que l'on masque, pour d'autres raison également

**Comment by djaccard** [comment]
oui, je trouve agréable de pouvoir chercher par username. je le fais régulièrement. Il y a des cas où il peut y avoir 2 "pierre dupont" ou une personne avec deux comptes, mais username différents => soit l'adresse soit le user name permettent de différencier.

**Comment by djaccard** [comment]
et si on met les username entre parenthèse après le nom dans la listes des trainers qvec qui ont a partagé, on évite les situations comme: 
![capture d ecran 2016-03-07 a 08 29 23](https://cloud.githubusercontent.com/assets/1556490/13563078/c331d634-e43e-11e5-8201-b0d70074d3ff.png)

**Comment by maxencelaurent** [comment]
ça  a l'air corrigé, je ferme

![image](https://cloud.githubusercontent.com/assets/6583528/21771396/7c53a9fe-d687-11e6-95e8-d6d13ece5d18.png)
