### ISSUE TITLE
Edition page: new / add element

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1146]
On n'est pas cohérent entre le bouton sur la colonne centrale et celui de la colonne de droite: une fois new, une fois add pour un même contenu.

Mettre les deux fois "Add"

Est-ce qu'il y a une raison à ce que ce bouton soit aux deux endroits ?

![capture d ecran 2015-11-30 a 05 09 09](https://cloud.githubusercontent.com/assets/1556490/11463378/d69931f6-9720-11e5-8205-eedb484fc5f3.png)

**Comment by CiGit** [comment]
Je pense que la difference vient de:
*Add* signifie ajouter à **cet** élément. Certainement utile si tu as une sous-liste
*New* signifie ajouter à la page, l'élément racine. Créer un nouvel élément (le résultat est exactement le même)
