### ISSUE TITLE
Add question folder: enlever "select"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1149]
Une fois le dossier de questions choisi, il y a un select qui apparait, mais il n'a pas d'utilité.
Est-ce qu'on peut l'enlever ?

![capture d ecran 2015-11-30 a 05 21 35](https://cloud.githubusercontent.com/assets/1556490/11463479/60690a0e-9722-11e5-995a-2b1d3f1aee9d.png)

**Comment by CiGit** [comment]
L'utilité c'est si tu veux aller dans un sous dossier!

**Comment by djaccard** [comment]
oui, mais il était mis même lorsqu'il n'y avait pas de sous-dossier (ie rien à sélectionner)
On dirait que c'est corrigé.
