### ISSUE TITLE
Add choice => add answer

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1150]
Remplacer add choice par add answer

![capture d ecran 2015-11-30 a 05 26 00](https://cloud.githubusercontent.com/assets/1556490/11463503/eb67af84-9722-11e5-9975-d629d76eab73.png)

**Comment by CiGit** [comment]
il y a actuellement au niveau de l'interface
* *Question*
  * *Choice*
    * *Result*

Tu aimerais : 
* *Question*
  * __*Answer*__
    * *Result*

C'est presque similaire à *Result* de mon point de vue. Confusion ?

**Comment by djaccard** [comment]
On dirait que les gens comprennent mieux Questions-réponse que Question-choix.

Peut-être passer à : 
Question
