### ISSUE TITLE
Open page : target current page display

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1152]
Provoque de la confusion entre enitre page, current page display et les autres page display.
Quel est l'utilité ? Pour le page display courrant, on pourrait le choisir dans la liste des pages display ?
Est-ce qu'on ne devrait pas avoir juste "Entire page" et la liste des autres pages display ?

![capture d ecran 2015-11-30 a 05 34 20](https://cloud.githubusercontent.com/assets/1556490/11463578/476dec66-9724-11e5-9fec-f586680b5687.png)

**Comment by CiGit** [comment]
Explications sur le *Current page display* :
Il ouvre la page dans le *pageloader* courant, c'est à dire que c'est contextuel, le nom de celui-ci n'est pas défini, il dépend de l'emplacement de la page qui contient cet *Open page action*

----
Si tu as un autre nom à proposer, qui peut réduire cette confusion que tu notes, ce peut être une bonne idée.

**Comment by CiGit** [comment]
mettre un séparateur entre current et les autres noms de page
