### ISSUE TITLE
Afficheur dialogues: fonctionne pas pour un dossier de dialogues

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1153]
ok si on sélectionne un dialogue du dossier, mais pas pour afficher la liste des dialogues du dossier.
Ce serait bien que ça fonctionne pour le cours "créer son serious game" de lundi prochain.

![capture d ecran 2015-11-30 a 05 42 42](https://cloud.githubusercontent.com/assets/1556490/11463636/4ed806c0-9725-11e5-8d8b-d4c3324db464.png)

**Comment by CiGit** [comment]
#1147
Une liste ou un élément n'ont pas le même visuel. Doit-on aussi pouvoir afficher une liste de *Text* par exemple ?
