### ISSUE TITLE
Mails dans les spams

### ISSUE THREAD

**Issue by CiGit** [Heigvd/Wegas#1154]
Pour ceux du trainer: ouvrir sa boite mail perso (il verrait les adresses des étudiants, mais pas grave)

Pour le mot de passe: mettre un message "vérifier dans les spams" 

Ou trouver une solution pour que ça ne passe pas dans les spams....

**Comment by djaccard** [comment]
AU moins mettre message du type:
 Si vous n’avez pas reçu le message, vérifiez dans le dossier « Spam » ou « Courrier indésirable » de votre messagerie.

**Comment by CiGit** [comment]
![image](https://cloud.githubusercontent.com/assets/1453420/11655916/c0a46fd6-9db1-11e5-959d-3f3872166b54.png)
http://www.mail-tester.com/

**Comment by CiGit** [comment]
Ok sur gmail.
Ok sur heig-vd (mais vu ce qu'il laisse passer ces temps... j'espère bien)
Spam sur outlook online (hotmail): `X-Forefront-Antispam-Report: EFV:NLI;SFV:SPM;SFS:(28900001);DIR:INB;SFP:;SCL:5;SRVR:AM5EUR03HT061;H:SNT004-MC4F24.hotmail.com;FPR:;SPF:None;LANG:fr;`
