### ISSUE TITLE
PMG : gantt tâches planification

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1158]
je clique pour réserver, ça tourne, puis revient à blanc
si je change d'onglet et revient => réservé quand même
et autres comportements du style bizarre.
<img width="1070" alt="capture d ecran 2015-12-03 a 12 33 35" src="https://cloud.githubusercontent.com/assets/1556490/11559559/406b468c-99ba-11e5-81e5-53e491a7e2bd.png">

**Comment by maxencelaurent** [comment]
Je ne vois rien de ce genre moi... 

Quelle navigateurs/version ?
