### ISSUE TITLE
trainer dashboard plante

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1163]
à l'ouverture des notes du trainer, quand on commence à prendre des notes
<img width="1166" alt="capture d ecran 2015-12-15 a 08 42 57" src="https://cloud.githubusercontent.com/assets/1556490/11804928/fd2b97a8-a307-11e5-959c-d1cae55f40ae.png">
<img width="1440" alt="capture d ecran 2015-12-15 a 08 33 58" src="https://cloud.githubusercontent.com/assets/1556490/11804929/fed065e8-a307-11e5-9108-4868fd63bdf8.png">

**Comment by maxencelaurent** [comment]
ok, je sais ce que c'est

**Comment by maxencelaurent** [comment]
J'ai corrigé ce problème là, par contre, c'est en enlevant la synchro des nouvelles équipes.

Il faudra rebrancher cette syncho de manière un peu plus fluide
