### ISSUE TITLE
PMG: % dépenses courantes

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1166]
Onglet "Projet" - Dépenses courantes

On  dirait que: 
calcul % en fonction du BAC
légende "% du budget initial"

<img width="579" alt="capture d ecran 2015-12-17 a 14 21 09" src="https://cloud.githubusercontent.com/assets/1556490/11870783/feef4a3e-a4ca-11e5-8ab5-7e66190d423c.png">

**Comment by maxencelaurent** [comment]
et c'est lequel qui est juste ?

**Comment by djaccard** [comment]
Je propose de mettre tous les % sur la base du budget initial => conserver le texte, modifier le nombre.

Ou mettre les deux ?
- 90% du budget initial
- 106% du coût planifié
