### ISSUE TITLE
truc d'attente pas toujours visible

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1171]
Selon le fond d'écran, on le le voit pas bien.
Possibilité: mettre un fond grisé derrière le truc qui bouge
![capture d ecran 2016-01-05 a 13 54 23](https://cloud.githubusercontent.com/assets/1556490/12115616/fdf2d22a-b3b3-11e5-8da5-d3714ccdc06a.png)

**Comment by CiGit** [comment]
On avait enlevé le fond parce que cela donnait un effet de flash.
Plutôt mettre un *glow* sur les barres qui pourrait le faire ressortir un peu plus.
Et si par malchance il est toujours invisible, c'est à faire au cas par cas, i.e. dans le scénario
