### ISSUE TITLE
[PMG] Mise en page des actions 

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1175]
Le bouton submit est en dehors quand il n'y a pas de texte (cas le plus courant pour les actions/pmg)

![image](https://cloud.githubusercontent.com/assets/6583528/12193152/bcf44f4a-b5e5-11e5-848f-f0ec93a33229.png)

Quand il y a un peu de texte c'est pas mieux:
![image](https://cloud.githubusercontent.com/assets/6583528/12193220/4fbdc54a-b5e6-11e5-985b-54917d2b8159.png)

Et voilà quand il y a encore plus de texte : 
![image](https://cloud.githubusercontent.com/assets/6583528/12193229/6e00fbc6-b5e6-11e5-9148-3a8e8359e021.png)

**Comment by JarleHulaas** [comment]
Salut Maxence,

Merci pour ce message. J’ai fait une correction temporaire en ajoutant un ficher CSS comme scénariste dans PMG Artos version française et anglaise. Le résultat semble convenable, mais je veux réviser l’implémentation (une fois que j’aurai un peu avancé sur OncoSim), car il me semble que je suis parti dans une mauvaise direction.

Question: le bouton “Next phase” n’est plus actif bien que l’option “Force question replies” soit réglé sur false. Serait-ce une victime collatérale de mes modifications ?

Merci
-Jarle

**Comment by maxencelaurent** [comment]
Ok, on verra ça lundi.

Pour le bouton NextPhase qui est désactivé, c'est simplement à cause de la limite d'avancement, aucune soucis avec tes modif

**Comment by git-jarle** [comment]
Solved 6f68a23af204195db2fd999e67b51a7737a94b68
