### ISSUE TITLE
PMG: responsive player 

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1176]
![capture d ecran 2016-01-11 a 15 35 34](https://cloud.githubusercontent.com/assets/1556490/12236267/0b248b90-b879-11e5-8171-1878ea7059fa.png)

**Comment by maxencelaurent** [comment]
Just prevent this behaviour... Full solution should be to replace the in-line left menu (Home, Project, etc.) with such a drop-down list when there is not enough room.

**Comment by maxencelaurent** [comment]
Est-ce que ça a été arrangé récemment ?

**Comment by git-jarle** [comment]
Oui, juste avant No?l.

Le 3 janv. 2017 ? 17:47, maxencelaurent <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Est-ce que ?a a ?t? arrang? r?cemment ?

-
