### ISSUE TITLE
Chat: mise en forme

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1177]
On peut enlever le "me", "maxence" dans la barre de droite. On le voit déjà dans les en-tête des messages.
Mettre le "send" en vert.
On peut même enlever toute la barre de droite. ça laisserait plus de place aux messages. 
Est-ce qu'il y a un sens à garder tous les maxence joined, left ?

![capture d ecran 2016-01-25 a 16 18 33](https://cloud.githubusercontent.com/assets/1556490/12555000/5d5e6492-c37f-11e5-9ec6-d0e8397592c9.png)

**Comment by CiGit** [comment]
![image](https://cloud.githubusercontent.com/assets/1453420/12556048/536e424a-c384-11e5-822c-31d78a656841.png)

zone message plus large
tooltip Nom sur Initiale
