### ISSUE TITLE
pdf scénario: impacts pas en wysiwyg

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1180]
Est-ce qu'on arrive à améliorer ?

![capture d ecran 2016-02-01 a 15 06 05](https://cloud.githubusercontent.com/assets/1556490/12719567/194e20fe-c8f6-11e5-99af-ec2f1c937714.png)

**Comment by JarleHulaas** [comment]
Ce n'est pas tellement un problème de présentation, car il s'agit bien d'impacts touchant des variables inexistantes (supprimées par le scénariste après création de l'impact). Il faudrait éventuellement ajouter un message d'erreur "Unable to find variable" comme lors de l'édition en mode scénariste.

**Comment by djaccard** [comment]
bon, on clôt
