### ISSUE TITLE
Problème affichage des dates des versions

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1181]
game: 11702

![wp_20160201_15_05_02_pro](https://cloud.githubusercontent.com/assets/1556490/12719596/58849fc8-c8f6-11e5-9987-c815bcb94b17.jpg)

**Comment by CiGit** [comment]
Il faudrait l'indication du navigateur + version et OS + version.
La gestion des dates a légèrement changée dans une autre correction 53e67e9775b7645df3948f260e28715d8c1791cd
Le problème a peut-être disparu.
