### ISSUE TITLE
PMG: news depuis trainer

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1183]
ajouter la possibilité d'envoyer une news depuis les impacts simplifiés
actuellement seulement possible depuis impacts avancés
aura plus de sens lorsqu'il sera possible de faire l'impact sur toutes les équipes.

**Comment by CiGit** [comment]
La boite au lettre news ne devrait-elle pas être de type `GameScope` / `GameModelScope`

**Comment by maxencelaurent** [comment]
sisi -> GameScope

**Comment by maxencelaurent** [comment]
En fait, pas game scope, car l'info read/unread doit être fcn de l'équipe

**Comment by maxencelaurent** [comment]
new dashboard is coming
