### ISSUE TITLE
Mise en page questions à 1 réponse (type Actions PMG)

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1187]
Enlever la barre grise sur le valider.

<img width="636" alt="capture d ecran 2016-02-29 a 11 34 17" src="https://cloud.githubusercontent.com/assets/1556490/13392747/05473a9e-dedd-11e5-9fcd-2d4d7eaf264a.png">

**Comment by gitjarle** [comment]
Fix 72893b83a2b16e36a733b45c4b02f63006e0264b
