### ISSUE TITLE
Dashboard trainer: ordre alpha des équipes

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1190]
les équipes sont classées par ordre alpha (ce qui est bien), mais on dirait que c'est case sensitive. 
Si possible, mettre ordre alpha sans tenir compte des majuscules/minuscules.

<img width="326" alt="capture d ecran 2016-03-01 a 15 11 22" src="https://cloud.githubusercontent.com/assets/1556490/13429348/1506ba66-dfc0-11e5-8761-4b91a2391603.png">

**Comment by gitjarle** [comment]
Solved 9b64f94b7e8e19dbf283c448e3ec2754f9cd66a0
