### ISSUE TITLE
Gantt passé en réalisation alors qu'on est en planif

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1192]
partie belledemo, 2599776, créé par dominique
équipe domteam (joueur domplayer)
3 mars

**Comment by gitjarle** [comment]
D�sol�, �a c'est moi qui ai fait hier soir en pr�parant le cours! Y a pas de bug :-)

-Jarle

Le 3 mars 2016 � 12:18, dominique <notifications@github.com<mailto:notifications@github.com>> a �crit :


partie belledemo, 2599776, cr�� par dominique
�quipe domteam (joueur domplayer)
3 mars

-
