### ISSUE TITLE
Indicateurs (rabah)

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1195]
Je t'envoie un BUG identifié lors d'une partie, ou bien c'est une incompréhension.
Nous sommes en semaine 4, et l'indicateur Management and users en est à la semaine 6,
et les KPI Qality, schedule and cost sont à la semaine 5.

![capture d ecran 2016-01-13 a 12 43 51](https://cloud.githubusercontent.com/assets/1556490/13496491/bff422d8-e150-11e5-84f6-6cab04337e6a.png)

**Comment by maxencelaurent** [comment]
Et si on met les labels comme ça 

![image](https://cloud.githubusercontent.com/assets/6583528/21771163/8dcb9bca-d686-11e6-848d-8a8b868d4f6b.png)

**Comment by maxencelaurent** [comment]
en ligne
