### ISSUE TITLE
Introduction Budget intial: truc qui tourne => comportement étrange

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1198]
Je viens de faire la démo de comment entrer le budget initial en avant-projet (copie d'écran déjà passé en planif) 
=> ça tourne, les chiffres n'apparaissaient pas 
=> je réessaye d'introduire 
=> les chiffres apparraissent en retard 
=> je ne touche plus et les chiffres se modifient seuls: apparaissent, disparaissent, 
=> les participants rigolent ;-)

<img width="612" alt="capture d ecran 2016-03-09 a 13 45 41" src="https://cloud.githubusercontent.com/assets/1556490/13635737/0bda1c46-e5fe-11e5-88b1-f9efc14b3309.png">

**Comment by djaccard** [comment]
ça a refait la même chose aujourd'hui..

**Comment by maxencelaurent** [comment]
duplicate #1233
