### ISSUE TITLE
Problème affichage player PMG

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1200]
Navigateur: chrome
J'ai vu problème similaire sur safari (mais pas sur mon safari)

<img width="1365" alt="capture d ecran 2016-03-09 a 16 37 46" src="https://cloud.githubusercontent.com/assets/1556490/13641433/b03dd182-e618-11e5-8e94-939fbfcbdf66.png">

**Comment by git-jarle** [comment]
Solved 6f68a23af204195db2fd999e67b51a7737a94b68
