### ISSUE TITLE
Dashboard trainer: boutons refresh

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1201]
Mieux séparer visuellement les deux boutons.
Pour les noms peut être remplacer par:
- refresh team datas
- refresh teams (ou laisser refresh all ?)

<img width="317" alt="capture d ecran 2016-03-10 a 17 03 52" src="https://cloud.githubusercontent.com/assets/1556490/13675507/407184aa-e6e2-11e5-9b8d-45a52559441b.png">

**Comment by git-jarle** [comment]
Implémenté dans https://github.com/Heigvd/Wegas/commit/378ea35307dcd31e27942b8bfb09b64a9888b069
