### ISSUE TITLE
Planification: ajouter salaires actuellement affectés

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1203]
Dans l'onglet tâche, est-ce qu'on pourrait ajouter une colonne avec la salaire actuellement affecté (durée de la tâche * salaire des ressources affectées).
On aurait le salaire actuellement affecté, les frais fixes => aux étudiants d'entrer le BAC de la tâche.

**Comment by maxencelaurent** [comment]
Prêt à être mis en ligne !

**Comment by maxencelaurent** [comment]
en ligne
