### ISSUE TITLE
Stats: sélection des parties

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1204]
pourquoi certaines partie n'ont plus de nom ?
Est-ce qu'on pourrait ajouter les infos sur la partie: date création, nom trainer, nombre participants ?
<img width="325" alt="capture d ecran 2016-03-21 a 15 23 51" src="https://cloud.githubusercontent.com/assets/1556490/13921633/20b6671c-ef79-11e5-9cf8-516e7827ffd5.png">

**Comment by CiGit** [comment]
> pourquoi certaines partie n'ont plus de nom ?

Parce que la partie n'existe plus.

> Est-ce qu'on pourrait ajouter les infos sur la partie: date création, nom trainer, nombre participants ?

Si ce sont des informations qui existe dans la partie, oui, jusqu'à ce que la partie soit supprimée.

**Comment by CiGit** [comment]
Simplement: On devrait pouvoir récupérer les informations de GameAdmin
