### ISSUE TITLE
stats: generate all fonctionne pas

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1205]
je clique sur generate all 
=> ouvre nouvelle page, page actuelle est passée en grisé (on ne peut plu cliquer)
=> après 10'', page actuelle revient en normal (on peut de nouveau cliquer), mais la page ouverte reste vide => pas de statistiques

<img width="1333" alt="capture d ecran 2016-03-21 a 15 33 32" src="https://cloud.githubusercontent.com/assets/1556490/13921888/5948157a-ef7a-11e5-9eab-a0b651e70632.png">

**Comment by CiGit** [comment]
Il y a un soucis de génération de l'image.
