### ISSUE TITLE
Lobby player: les parties supprimées restent affichées

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1207]
il faut rafraichir la page pour qu'elles disparaissent

**Comment by maxencelaurent** [comment]
Quelle version ? Cache, pas cache ?

**Comment by maxencelaurent** [comment]
Lorsqu'on supprime une partie depuis l'interface animateur, elle reste dans le lobby des players jusqu'au prochain rafraîchissement

-> Pusher partout !
