### ISSUE TITLE
Pas possible de rjoindre une partie: clé accès invalide

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1210]
J'ai essayé avec plusieurs clé de jeu ouverts et je reçois le message "clé invalide"

**Comment by git-jarle** [comment]
Quelles clés, par exemple ?

**Comment by git-jarle** [comment]
Quelles clés, par exemple ?

De : dominique [mailto:notifications@github.com]
Envoyé : jeudi 19 mai 2016 15:05
À : Heigvd/Wegas <Wegas@noreply.github.com>
Objet : [Heigvd/Wegas] Pas possible de rjoindre une partie: clé accès invalide (#1210)


J'ai essayé avec plusieurs clé de jeu ouverts et je reçois le message "clé invalide"

**Comment by maxencelaurent** [comment]
pas nous...

**Comment by CiGit** [comment]
:tada:

**Comment by djaccard** [comment]
C'est bon !
hum... j'ai utilisé sur la version prod des clé de la dev
ok, il y a plus malin...

**Comment by maxencelaurent** [comment]
Bon, après bien des investigations, il apparait qu'il n'est pas possible de créer une partie sur WegasCache et la rejoindre depuis Wegas prod....

Je dis ça, je dis rien

**Comment by djaccard** [comment]
promis, je le ferai plus ;-)

**Comment by djaccard** [comment]
c'est pas synchronisé ces versions ?

**Comment by CiGit** [comment]
Non, on a peur que l'une soit trop rapide pour l'autre

**Comment by djaccard** [comment]
;-) 
plus pour longtemps
