### ISSUE TITLE
Création équipes

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1211]
Quand une personne crée une équipe, elle apparait chez les autres personnes connectées avant qu'elle apparaisse chez celui qui la crée (quand ça tourne encore chez celui qui la crée).
Si les autres cliquent pour rejoindre l'équipe avant que ça ait fini de tourner chez celui qui l'a créée, ça fait une erreur.

**Comment by CiGit** [comment]
Le changement qui avait été fait a été annulé pour le moment.

**Comment by maxencelaurent** [comment]
fix in ddee10d8c5546341ea6ab3860bda521a01feebb7
