### ISSUE TITLE
Responsive dashboard trainer

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1212]
On dirait qu'on reste au niveau le plus petit (chrome)

![capture d ecran 2016-05-20 a 15 53 42](https://cloud.githubusercontent.com/assets/1556490/15429888/2e7cf0f6-1ea3-11e6-8719-2429115ea1fe.png)

**Comment by git-jarle** [comment]
Fix 378ea35307dcd31e27942b8bfb09b64a9888b069
