### ISSUE TITLE
Dashboard trainer: mise en forme boutons rafraichissement

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1213]
Actuellement, le bouton pour le refresh all est autant prêt de chaque texte de légende.
Faire deux "groupes" en rapprochant le bouton du texte correspondant et laisser un plus grand espace entre les deux groupes.

![capture d ecran 2016-05-20 a 15 55 55](https://cloud.githubusercontent.com/assets/1556490/15429973/8fd9e804-1ea3-11e6-9bb8-84d1d8c2643a.png)

**Comment by git-jarle** [comment]
Fix 378ea35307dcd31e27942b8bfb09b64a9888b069
