### ISSUE TITLE
synchronisation player: next phase

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1214]
Actuellement, si un player clique sur next phase, ça tourne chez lui, mais pas chez les autres. 
Pour éviter le passage de deux phases à la fois, ce serait bien que les autres ne puissent pas cliquer sur next phase tant que l'avancement n'est pas terminé.

**Comment by maxencelaurent** [comment]
Partiellement corrigé: Il peut toujours cliquer, mais il ne se passera rien de plus si un autre avancement est déjà en cours

Idéalement, on devrait trouver une solution qui permette de généraliser ce comportement (je pense principalement ici au réponse aux questions)
