### ISSUE TITLE
cache: problème de scénario ou autre ?

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1215]
J'ai créé une partie avec un des deux scénarios artos et ouvert l'interface d'animation de cours.
![capture d ecran 2016-05-24 a 15 54 25](https://cloud.githubusercontent.com/assets/1556490/15506433/ee520642-21c7-11e6-887f-a693f4ed9c50.png)

**Comment by maxencelaurent** [comment]
a priori c'est un problème du scénario. Je regarderai ça de plus près demain matin

**Comment by maxencelaurent** [comment]
autre en fait...

**Comment by maxencelaurent** [comment]
arf

**Comment by CiGit** [comment]
Il y a 3 problèmes soulevé ici:
```js
var advLimitDesc;
try {
    advLimitDesc = Variable.find(gameModel, "advancementLimit");
} catch(e){}
return advLimitDesc !== undefined;
```
1. Avec le cache, lors de la création, il n'y a pas d'utilisateur
2. La variable Advancement Limit est nommée (sur wegas db maintenant) 7x `advancementLimit` et 81x `advancementLimit_`
3. Il y a un return en fin de programme, ce qui n'est pas autorisé sur le serveur. Il retourne simplement la dernière instruction.

En corrigeant le point 1, le reste devient invisible:
il n'y a plus d'erreurs du côté client pour évaluer ce code. Il est donc évalué côté client et il retourne dans `false` dans tous les cas où la variable n'existe pas.
Je n'ai pas l'impression que ce code servent vraiment ...
