### ISSUE TITLE
PMG - Properties : droits d'avancement

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1216]
comportement bizarre lorsqu'on passe la souric sur les périodes (le vert ne ient pas toujours, cases, qui bougent , vert vient si la souris en dehors des zones).
<img width="633" alt="capture d ecran 2016-05-30 a 13 21 09" src="https://cloud.githubusercontent.com/assets/1556490/15648256/8ab46430-2669-11e6-8d28-71c3796734cc.png">

**Comment by maxencelaurent** [comment]
semble corrigé
