### ISSUE TITLE
Stats: parties avec seulement le no

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1225]
Difficilement utilisable...
Il faudrait:
- conserver le nom de la partie (même si supprimée)
- conserver si possible le nom du scénariste et la date de création
- si pas possible de conserver nom partie, alors la supprimer des stats (ou au moins de la liste déroulante), mais ce serait dommage...

![capture d ecran 2016-07-04 a 11 22 08](https://cloud.githubusercontent.com/assets/1556490/16556327/b25f8916-41d9-11e6-858b-bcab405653d7.png)

**Comment by CiGit** [comment]
__Sans changer completement la partie enregistrement__ Il est possible de conserver le nom de la partie (non rétroactif). L'enregistrer avec chaque enregistrement. La partie pourrait avoir plusieurs nom dans le cas d'un renommage en court de partie.


Le scénariste est-il le _trainer_ ? Il peut y en avoir plusieurs et cela peut changer en cour de partie aussi.

**Comment by djaccard** [comment]
oui, on conserve le nom de la partie à chaque enregistrement. Normalement, on ne renomme pas une partie en cours. Mais si ça arrive, ça donnerait deux parties ?

Oui, conserver le nom du trainer et pas du scénariste. S'il y en a plusieurs, conserver tous (ou le premier seulement). Normalement ne chang epa s en cours de partie. Mais si ajout d'un nouveau trainer: soit on conserve tous les trainer (le mieux), soit seulement le premier.
