### ISSUE TITLE
branche à tester: ouvrir dashboard scénariste plante

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1229]
ne va pas plus loin...
on dirait que ça fonctionne avec les autres scénarios

<img width="1237" alt="capture d ecran 2016-08-29 a 09 05 57" src="https://cloud.githubusercontent.com/assets/1556490/18043448/3817c66c-6dc8-11e6-87a0-cd689ecdbf35.png">

**Comment by CiGit** [comment]
Il semblerait que ce soit provisoire.
