### ISSUE TITLE
les pastilles "mails non lus" ne se mettent pas à jour

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1236]
parfois on a 5 mails non lus affichés dans la pastille, mais il n'y en a que 3.

**Comment by git-jarle** [comment]
Je n'ai pas réussi à reproduire le problème (scénario Belleville)

**Comment by maxencelaurent** [comment]
Pas réussi non plus

**Comment by git-jarle** [comment]
Ce problème a l'air d'être résolu
