### ISSUE TITLE
Réponses conditionnelles sans résultat défini par défaut

### ISSUE THREAD

**Issue by git-jarle** [Heigvd/Wegas#1247]
La suppression du résultat par défaut peut mettre la réponse dans un état indéfini. Quelquefois, c'est toute la réponse qui disparaît avec le résultat par défaut. 

A l'exécution, la validation de la réponse produit alors une exception avec un popup affichant "null has no function 'trim'".

![capture](https://cloud.githubusercontent.com/assets/5621120/19930296/13ca1f8a-a108-11e6-9e71-904bbdfeaa38.PNG)

**Comment by CiGit** [comment]
Il n'y a plus de soucis avec un choix qui pointe vers null. Le serveur choisi la première.
Il y a eu passablement de changement au niveau MCQ ;-)
