### ISSUE TITLE
Player - join team

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1249]
Si on clique en dehors de la fenêtre, on se retrouve dans le lobby player, comme si on avait cliquer sur la croix pour fermer la fenêtre.
Il faudrait qu'un clic en dehors de la fenêtre n'ait pas d'effet.

![capture d ecran 2016-11-07 a 12 26 29](https://cloud.githubusercontent.com/assets/1556490/20056279/a243a7a0-a4e5-11e6-9ad5-7dce3ec4b73b.png)

**Comment by CiGit** [comment]
C'est pourtant un comportement courant des fenêtres _modal_
