### ISSUE TITLE
PMG Gantt planif

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1250]
Est-ce qu'on ne devrait pas enlever la case grisée pour montrer sur laquelle on pointe ? Quand on se déplace vite, ça fait des effets de traces qui suivent le pointeur.
=> Juste laisser le pointeur en main.

<img width="1128" alt="capture d ecran 2016-11-07 a 15 04 11" src="https://cloud.githubusercontent.com/assets/1556490/20060495/b6295632-a4fb-11e6-8975-2ac658228ce6.png">

**Comment by CiGit** [comment]
Si je me déplace **vite** il n'y a rien qui apparaît. Je trouve que cela donne une bonne indication sur ce qui va se passer si je clique. 
Avec uniquement le pointeur, il y a bien l'indication _je peux cliquer_ mais sans deviner le résultat.
