### ISSUE TITLE
pdf scénario: mese en form mails

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1251]
il faudrait enlever le formatage html

<img width="661" alt="capture d ecran 2016-11-08 a 13 25 48" src="https://cloud.githubusercontent.com/assets/1556490/20099094/0de65a94-a5b7-11e6-8d72-928decea0fd6.png">

**Comment by maxencelaurent** [comment]
![image](https://cloud.githubusercontent.com/assets/6583528/20709481/f6dc3320-b635-11e6-9816-64edf04ea9ea.png)
