### ISSUE TITLE
Trainer: partage parties

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1253]
Sur chrome, si je sélectionne le trainer ave qui partager, il ne se passe rien. 
Sut firefox, ça fonctionne.

<img width="1197" alt="capture d ecran 2016-11-22 a 13 37 29" src="https://cloud.githubusercontent.com/assets/1556490/20525589/75feb324-b0c0-11e6-9de0-0d2f5f647bc3.png">

**Comment by git-jarle** [comment]
Je n'ai pas pu reproduire le bug. Chez moi chrome fonctionne aussi.

**Comment by CiGit** [comment]
Je n'en ai pas vu la reproduction, et vu la date, je pense qu'on peut fermer.
