### ISSUE TITLE
Stats ne fonctionnent plus

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1260]
N'affiche plus rien...

![capture d ecran 2016-11-28 a 09 24 43](https://cloud.githubusercontent.com/assets/1556490/20661017/b68d40be-b54c-11e6-873f-19c6c37ec1c2.png)
![capture d ecran 2016-11-28 a 09 25 32](https://cloud.githubusercontent.com/assets/1556490/20661020/b7ef8e8a-b54c-11e6-852b-a18f48e7a109.png)

**Comment by maxencelaurent** [comment]
serveur neo4j crash.

j'ai ça dans comme log :
Nov 28 09:46:12 localhost systemd[1]: Starting LSB: Neo4j Graph Database server...
Nov 28 09:46:12 localhost neo4j-service[13706]: WARNING: Max 1024 open files allowed, minimum of 40 000 recommended. See the Neo4j manual.
Nov 28 09:46:13 localhost neo4j-service[13706]: Starting Neo4j Server...WARNING: not changing user
Nov 28 09:46:19 localhost neo4j-service[13706]: process [13830]... waiting for server to be ready....... Failed to start within 120 seconds.
Nov 28 09:46:19 localhost neo4j-service[13706]: Neo4j Server failed to start, please check the logs for details.
Nov 28 09:46:19 localhost neo4j-service[13706]: If startup is blocked on a long recovery, use '/var/lib/neo4j/bin/neo4j start-no-wait' to give the startup more time.

**Comment by maxencelaurent** [comment]
solution temporaire: lancer neo4j en mode console: 

sudo su - neo4j
/var/lib/neo4j/bin/neo4j console &

C'est pas beau, mais ça marche... Je ne comprend pas pourquoi neo4j start ne fonctionne pas

**Comment by maxencelaurent** [comment]
OK, il fallait rebooter le server après avoir modifier la config
