### ISSUE TITLE
Etudiants en Guest ?

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1261]
Je ne sais pas si c'est un bug, mais en rechercahnat autre chose, je suis tombé sur cette partie avec des équipes et tous les players "guest" dans chaque équipe.

Une idée de comment ça a pu arriver ?

![capture d ecran 2016-11-28 a 13 06 07](https://cloud.githubusercontent.com/assets/1556490/20667807/97b72a8c-b56b-11e6-86d8-5fe38a9fef78.png)

**Comment by CiGit** [comment]
1. Les étudiants se sont tous nommés _Guest_
1. L'adresse _guest_ a été donnée par le prof
1. Les étudiants on réussi à déduire l'adresse _guest_ à partir de la clé
1. Un bug de l'interface: Ils ont pu entrer la clé alors qu'ils étaient connecté en _Guest_

**Comment by maxencelaurent** [comment]
see #1331
