### ISSUE TITLE
admin -  users

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1262]
j'ouvre le player Lhotte fabrice et modifie ses droits.
=> je n'arrive pas savuer. Message: mot de passe pas identique
Si j'essaye de copier le mot de passe dans confirmer, ça me le copie avec le double de points.
![capture d ecran 2016-12-05 a 14 36 58](https://cloud.githubusercontent.com/assets/1556490/20886907/a6bbc3ac-baf8-11e6-99a9-65500fd3899d.png)

**Comment by CiGit** [comment]
Tu as essayé de modifier le mot de passe ou les droits??
Parce que pour modifier les droits, la case mot de passe est initialement vide et doit le rester si tu ne veux pas changer le mot de passe. 
Tu ne peux pas copier un champ "mot de passe" `*****` du moins dans les navigateurs que je viens de tester. Ton presse papier contient l'ancienne valeur.

**Comment by maxencelaurent** [comment]
même si ça me semble logique, cela ne me parait pas hyper clair dans l'interface. Est-ce qu'on pourrait masquer les deux champs password à moins que l'on clique explicitement sur "Changer le mot de passe" ? ou un truc du genre ?

**Comment by git-jarle** [comment]
Fixed 5bc33435ce9c9f468a512f64c0d5f04eb3154838
