### ISSUE TITLE
Plus possible d'écrire dans le lobby

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1266]
on n'arrive plus à entrer du texte dans:
- champ de recherche
- paramètre scénario (par exemple modifier name dans copie écran)

![capture d ecran 2017-01-13 a 09 19 51](https://cloud.githubusercontent.com/assets/1556490/21922966/b8462e68-d971-11e6-89e6-6ddfe34e0643.png)

**Comment by djaccard** [comment]
en fait, je réessaie et je vois que c'est lent à saisir ce qu'on tape au clavier. 

je suppose qu' avant, c'était tellement lent qu'après quelques secondes sans réponse à l'écran de ce que j'écrivais, j'ai pensé qu'on ne pouvait plus écrire.

**Comment by git-jarle** [comment]
En fait la lenteur est très dépendante du nombre de scénarios ou de parties chargé dans le lobby: la liste est filtrée à chaque caractère tapé dans un champ de saisie.
C'est un problème propre à l'outil JavaScript Angular utilisé dans l'implémentation du lobby.
Je travaille dessus aujourd'hui.

-Jarle

**Comment by git-jarle** [comment]
Fixed 9f97876ea8e05881db1774c2616f862fc04882df
