### ISSUE TITLE
Clé en rouge

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1267]
Il y a des clés en rouge sur les jeux existants
Quelles conséquences ?
![capture d ecran 2017-01-13 a 09 19 51](https://cloud.githubusercontent.com/assets/1556490/21922990/e50a825a-d971-11e6-894f-11c60a2dcdb9.png)

**Comment by CiGit** [comment]
Il serait peut-être judicieux de donner un message explicatif.
Un message comme celui-ci `^([a-zA-Z0-9_-]|\\.(?!\\.))*$` pour tout le monde

**Comment by git-jarle** [comment]
On peut le mettre en ligne ?

**Comment by CiGit** [comment]
Oui, mais il n'y a pas de message explicatif dans le cas où le token ne passe pas le test: `^([a-zA-Z0-9_-]|\\.(?!\\.))*$`.
Raison pour laquelle j'ai ré-ouvert cette issue.

**Comment by git-jarle** [comment]
Fixed e23b8066b8856bad8e6a6210375f3b3bcba4baf0
