### ISSUE TITLE
PMG (scénario Construction v.2): erreur "out of range" dans script nextPeriod()

### ISSUE THREAD

**Issue by git-jarle** [Heigvd/Wegas#1269]
PMG (scénario Construction v.2): Dans la phase ‘Mise en Service’ (Clôture) du projet, dans laquelle il n’y a pour le moment aucun contenu (ni Action ni Question), quand on clique sur ‘Next period’ vient le message d’erreur suivant :

![picture1](https://cloud.githubusercontent.com/assets/5621120/21954302/6584457a-da4d-11e6-8215-ddc7a392ca63.png)

**Comment by maxencelaurent** [comment]
il manque le dossier pour les questions de la phase 4 !
