### ISSUE TITLE
Admin users: guest users

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1277]
L'interface se rempli de Guest users. Il me semble qu'on ne les voyait pas avant (ou est qu'il y en avait moins?)

Est-ce qu'on pourrait ne pas les présenter. De mon côté je n'en ai pas l'utilité. Et vous ? 

Au passage est-ce qu'on pourrait afficher les users classés comme dans le "WHO": admin, trainer/scénariste, players ?

![capture d ecran 2017-02-02 a 11 19 52](https://cloud.githubusercontent.com/assets/1556490/22545655/e50ca9e0-e939-11e6-9455-bae442fdf1d1.png)

**Comment by djaccard** [comment]
Ah...
est-ce que les CJ-users sont des test users à Cyril Junod ? les tests ont commencé sur la prod ?

**Comment by CiGit** [comment]
Oui ce sont mes utilisateurs de test qui datent des anciens tests.
Je les ai laissé pour de futures? test
