### ISSUE TITLE
Admin users: users pas tous affichés

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1278]
Je ne trouve qu'un Jaccard (alors qu'on est une famille nombreuse):
![capture d ecran 2017-02-02 a 11 27 34](https://cloud.githubusercontent.com/assets/1556490/22545917/0f436c70-e93b-11e6-8197-e426d472a1a7.png)

Si je scroll et revient, je trouve Arnaud:
![capture d ecran 2017-02-02 a 11 29 45](https://cloud.githubusercontent.com/assets/1556490/22545932/1eb4f05c-e93b-11e6-90c3-177f19f87f75.png)

Mais comment Arnaud peut-il être là si je n'existe pas ?

Avec la recherche, j'en trouve plus: 
![capture d ecran 2017-02-02 a 11 32 27](https://cloud.githubusercontent.com/assets/1556490/22545978/4bde0c26-e93b-11e6-924d-ac623c39b252.png)

**Comment by git-jarle** [comment]
Fixed 7d83ac7ea024f107d223c8f2936f244713a1020d
