### ISSUE TITLE
Vérifier les accents dans les e-mails envoyés depuis le dashboard

### ISSUE THREAD

**Issue by git-jarle** [Heigvd/Wegas#1286]
Il semble que les accents ne passent pas toujours (peut-être dépendant du navigateur Firefox utilisé pour l'envoi ou de restrictions sur le format HTML dans le client e-mail de la personne ayant signalé le bug).

```
Exemple:
De : Val rie C. via Wegas <noreply@albasim.ch<mailto:noreply@albasim.ch>>
Envoyé : lundi 27 février 2017 20:24
À : C. Valerie
Objet : Retour CoPil

Bonsoir, Suite   l? tude de votre projet, le comit  de s lection des projets a le plaisir de vous informer que votre projet a retenu toute leur attention. Nous vous autorisons donc   entamer la phase de planification. Bien cordialement. Le Comit  de S lection des Projets
________________________________
Sent by Val rie C. from albasim.ch<http://albasim.ch>

```

Vérifier non seulement le corps du message mais aussi le traitement des accents dans le sujet du mail et dans le nom du user qui l'envoie (champ From), où les possibilités d'encodage sont plus restreints.

Actuellement l'encodage est le suivant et les accents sont retransmis correctement dans le corps du message, envoyé depuis Chrome:
MIME-Version: 1.0
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: 7bit

**Comment by CiGit** [comment]
Maintenant: `Content-Type: text/html; charset="utf-8"`
