### ISSUE TITLE
Pas possible rejoindre équipe

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1297]
Si je clique sur rejoindre équipe www => message erreur.

Mais parfois si on re essaye ça passe

![capture d ecran 2017-03-30 a 12 19 04](https://cloud.githubusercontent.com/assets/1556490/24499800/35265c0c-1543-11e7-9eaf-5d5277d48231.png)

**Comment by maxencelaurent** [comment]
Je pense que j'ai identifié la source du problème... Le plus dur reste à faire ...
