### ISSUE TITLE
Force question replies : message

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1298]
Essayé de faire avancement période sans avoir réondu à toutes les questions, avec le force question replies activé.
Message expected error null

A remplacer par" vous devez répondre aux questions avant de pouvoir passer à la période/phase suivante"
![capture d ecran 2017-03-30 a 13 44 29](https://cloud.githubusercontent.com/assets/1556490/24502711/37b5b894-154f-11e7-9c01-82dbfee3b2ba.png)

**Comment by maxencelaurent** [comment]
De mon côté, j'ai bien 
![image](https://cloud.githubusercontent.com/assets/6583528/24503077/deb32b08-1550-11e7-80eb-2de6b786757d.png)

Je pense que l'erreur que tu as rencontrée est la même que #1297
