### ISSUE TITLE
Rejoindre partie: deux fois depuis navigateurs différents

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1300]
Ok, il faut chercher à faire faux, mais si on fait:
- deux navigateurs ouverts avec même joueur connecté
- navigateur 1: player rejoint la partie et son équipe
- navigateur 2: même player entre la clé => pas de message clé invalide => proposition liste équipe => plante quand on essaye rejoindre une équipe.

ça fonctionne normalement si sur le navigateur2 on rafraichi la page avant d'essayer de rejoindre.

**Comment by maxencelaurent** [comment]
Reproductible sur la version 2.5

**Comment by maxencelaurent** [comment]
#1331

**Comment by maxencelaurent** [comment]
cf #1207
