### ISSUE TITLE
Changement de rôle anim-scén-player

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1301]
Quand c'est lent, il n'y a pas vraiment de retour système. On dirait que c'est bloqué.
Est-ce qu'on pourrait mettre un truc qui tourne en haut à gauche du bouton de changement, à la place des trois lignes (ou une ligne pendant le changement) ?
à discuter...

**Comment by git-jarle** [comment]
Résolu en restaurant une version améliorée du scroll infini (paginé) qui était en vigueur avant. Le navigateur est donc beaucoup moins sollicité. L'inconvénient, c'est que la taille et la position de la scrollbar ne sont pas représentatifs du nombre effectif de parties ou scénarios dans la liste. Pour y remédier un peu, on pourrait afficher ce nombre dans le titre.
