### ISSUE TITLE
Edition page: bloqué au "save button"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1303]
J'ai ajouté l'impact sur variable on clic => save => tourne sans arrêt.
Raffrachi page => impact pas sauvé => réintroduit impact et savé et tout fonctionne.

![capture d ecran 2017-03-31 a 10 24 24](https://cloud.githubusercontent.com/assets/1556490/24542603/90b54434-15fc-11e7-9eb6-df1ec8850dba.png)

**Comment by maxencelaurent** [comment]
Probablement lié à la correction temporaire du problème de hier
