### ISSUE TITLE
On perd les pages des game model

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1304]
J'ai créé un game model (tc1) avec deux pages, afficheur questions, afficheurs variables. 
Testé en scénariste, fonctionne.

Ensuite: lobby => copié le game model (tc1(2))
Dans tc1(2), il n'y a plus aucune page
Dans tc1, il reste une page, mais qui a été renommée unnamned (je l'avais appellée Main). La deuxième page a disparu.
![capture d ecran 2017-03-31 a 10 35 52](https://cloud.githubusercontent.com/assets/1556490/24542948/dffee1de-15fd-11e7-8046-f7dd07abfb54.png)

Si je rouvre TC1 depuis un autre navigateur: je retrouve mes deux pages.

Si je rafraîchi dans le navigateur oì il y a le problème, ça revient en ordre pur TC1, mais pas pour la copie tc1(2)

**Comment by maxencelaurent** [comment]
idem #1303

**Comment by djaccard** [comment]
il y a l'air d'y avoir d'autres problèmes similaires liés: je ferme le game model et le rouvre => je vois pas toutes les pages. Je raffraichi et ok
