### ISSUE TITLE
Game model: erreur au clic sur lien image

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1305]
J'ai cliqué pour ouvrir une image en lien dans le texte de la question 1 => planté
![capture d ecran 2017-03-31 a 10 54 42](https://cloud.githubusercontent.com/assets/1556490/24543633/96c16ed0-1600-11e7-82b6-381fbc2068b6.png)

**Comment by maxencelaurent** [comment]
idem #1303
