### ISSUE TITLE
Légendes infos utilisateurs

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1306]
A la création des comptes ou lors de l'édition des users, on ne sait plus ce qui est dans les champs. La plupart du temps, c'est ok, mais parfois c'est ennuyant.

<img width="542" alt="capture d ecran 2017-04-04 a 14 23 25" src="https://cloud.githubusercontent.com/assets/1556490/24656669/a4e45ffe-1943-11e7-8cb5-1c6be7a41923.png">
<img width="893" alt="capture d ecran 2017-04-04 a 14 22 39" src="https://cloud.githubusercontent.com/assets/1556490/24656674/a673501e-1943-11e7-9dc1-73d3bb724dc9.png">

**Comment by git-jarle** [comment]
Fixed 69a1308252e5e1e51d9ee4208f2a5cbc607f4e6a
