### ISSUE TITLE
Users en lignes pas à jour

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1312]
Si je me connecte-déconnecte avec plusieurs comptes, ensuite je vais dans admin/Who => tous les users avec lesquels je me suis connectés sont présents, yc ceux avec lesquels je me suis déconnecté entre temps.
Rafraichir avec es flèches ne change rien
juste un truc style "pusher pas branché sur wegas3" ou autre problème ?
![capture d ecran 2017-04-20 a 07 18 38](https://cloud.githubusercontent.com/assets/1556490/25214881/45500076-259a-11e7-9075-94d3190334d9.png)

**Comment by CiGit** [comment]
Je suppose que c'est parce que (le) les onglets sont encore ouverts et qu'on ne déconnecte pas sur un *logout*.

**Comment by maxencelaurent** [comment]
précisions: c'est uniquement lorsqu'on logoutdepuis le lobby. Si je me déconnecte depuis qqch en YUI, ça fonctionne bien.

Ce n'est pas spécifique à wegas3

**Comment by CiGit** [comment]
Ce ne serait pas parce que *logout* -> `url.reload()` ?
