### ISSUE TITLE
Files: public-privé

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1313]
le fonctionnement du bouton public-privé est étrange. Une fois le privé utilisé, difficile de revenir en arrière.

**Comment by CiGit** [comment]
C'est à dire?
Lorsque le hiérarchie est privée, tout ce qui se trouve en dessous est privé.
Il est possible de spécifier un dossier ou un fichier uniquement en priver.

Il est vrai qu'il est difficile de savoir d'un coup d'oeil si on a mis tout en privé ou chaque élément individuellement

**Comment by djaccard** [comment]
on regardera ensemble la semaine prochaine.

**Comment by maxencelaurent** [comment]
1) Problème de sync des cadenas sur cluster
2) Problème de compréhension entre le verrou par fichier, le verrou hérité d'un dossier parent ou le verrou général
3) ne devrait pas ouvrir les fichiers directement quand on clique dessus

**Comment by CiGit** [comment]
1. A vérifier si c'est uniquement les cadenas. cf 2.
2. Les fichiers seront privés. Il n'y a plus de réel utilité à les avoir public. Disparition de private / public
3. Inversion des actions ouvrir / editer
