### ISSUE TITLE
Déplacement varaiables - mise à jour dans 2ème navigateur

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1314]
1er navigateur: je sors une variable d'un dossier et la remonte à la racine
2ème navigateur: la variable disparait du dossier, mais n'apparait pas à la racine. Ok si on rafraîchi la page.

**Comment by maxencelaurent** [comment]
reproductible sur version actuelle

**Comment by maxencelaurent** [comment]
fixed sur payara-micro

Je vous laisse volontiers vérifier si cela fonctionne bien (création de variables à la racine, déplacement de variable depuis ou vers la racine)

**Comment by maxencelaurent** [comment]
sur https://wegas3.albasim.ch
