### ISSUE TITLE
null Assignment NPE

### ISSUE THREAD

**Issue by CiGit** [Heigvd/Wegas#1319]
It occurred on wegas3 (**PMG**)

An assignment was null in a ResourceInstance's assignment on one of both server's cache.
This causes NPE on server js and client side. `null.myFn()`
### server
```
com.wegas.core.exception.client.WegasScriptException: TypeError: null has no such function "getTaskDescriptorId"
com.wegas.core.exception.client.WegasScriptException: TypeError: Cannot get property "taskDescriptor" of null 
```
### client
```js
taskD = tasks[assignment.get("taskDescriptorId")]; // Cannot read property 'get' of null
```
wegas-pmg-client.js:197

### Reproduction
I don't know ... (yet)

**Comment by maxencelaurent** [comment]
looks like the cache coordination issue fixed by setting cacheCorrdinationType to Invalidate
