### ISSUE TITLE
Gantt: enlever truc gris qui suit la souris

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1324]
plus perturbant qu'autre chose...
juste laisser la souris en main et ça suffit pour savoir sur quelle case on pointe.
<img width="208" alt="capture d ecran 2017-07-03 a 14 08 12" src="https://user-images.githubusercontent.com/1556490/27792270-2dbdd00c-5ff9-11e7-865a-f8ab229f535c.png">

**Comment by maxencelaurent** [comment]
duplicate #1250
