### ISSUE TITLE
Ressource pas en gras

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1325]
Pourquoi Gian est en gras, mais pas Anna ?
Je laisse la partie dans l'état (gameId=7694111)
<img width="1109" alt="capture d ecran 2017-07-04 a 13 14 35" src="https://user-images.githubusercontent.com/1556490/27828115-e0d82ab8-60ba-11e7-8780-4370fb2be06c.png">
<img width="813" alt="capture d ecran 2017-07-04 a 13 15 16" src="https://user-images.githubusercontent.com/1556490/27828117-e2aa75d0-60ba-11e7-9964-c6cf8f8e611b.png">

**Comment by maxencelaurent** [comment]
En gras c'est ceux qui travailleront lors de la prochaine périuode, or Anna sera indisponible.

![image](https://user-images.githubusercontent.com/6583528/27828257-96c0ae22-60bb-11e7-9131-0f9f6991694a.png)

**Comment by djaccard** [comment]
ah, ben évidemment !
