### ISSUE TITLE
Admin Lobby: show scenario creator in listing

### ISSUE THREAD

**Issue by git-jarle** [Heigvd/Wegas#1327]
When connected with admin rights and viewing the list of scenarios, each scenario should show its creator and be highlighted when the current user is the creator. E.g., print the creator name in a different color or list first those scenarios created by the current user.

**Comment by CiGit** [comment]
Ref #1321

**Comment by git-jarle** [comment]
Same request for the session list.

**Comment by git-jarle** [comment]
Fixed 63fa011ef8833347e064e85b852feec099a7c5b6

**Comment by maxencelaurent** [comment]
pas visible dans la corbeille ?

**Comment by maxencelaurent** [comment]
![image](https://user-images.githubusercontent.com/6583528/31448927-e2509022-aea5-11e7-9359-683ebab29055.png)

Artos 2 est à Laura, les autres à root. Je ne sais pas lesquels j'ose supprimer pour de vrai

**Comment by git-jarle** [comment]
Argh! Poubelle de luxe!
Bon voyons déjà si la solution proposée vous convient pour les scénarios/parties encore actives.

**Comment by maxencelaurent** [comment]
disons que pour moi, afficher en premier mes scenarios/parties ne change pas grand chose, le nom du créateur à côté du nom me suffit largement

Si dans la corbeille le nom du créateur s'affiche aussi ça serait super
