### ISSUE TITLE
Locking exceptions when updating object descriptors

### ISSUE THREAD

**Issue by git-jarle** [Heigvd/Wegas#1330]
When modifying properties of an object descriptor, an OptimisticLockException is often raised (about 50% of the time), like this one (from a client-side script in the SFG game): 

Y.Wegas.App: Error sending POST request : http://localhost:8080/Wegas/rest/Editor/GameModel/2302/VariableDescriptor/Script/Run/123836, {"@class":"Script","content":"Variable.find(gameModel, \"corrige\").getDefaultInstance().setProperty(\"CompteCrédit1\", \"2200\");"}: 
 Server reply {
	"@class": "ManagedResponse",
	"deletedEntities": [],
	"updatedEntities": [],
	"events": [
		{
			"@class": "ExceptionEvent",
			"exceptions": [
				{
					"@class": "WegasConflictException",
					"localizedMessage": "javax.persistence.OptimisticLockException: Exception [EclipseLink-5011] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.OptimisticLockException\r\nException Description: One or more objects cannot be updated because it has changed or been deleted since it was last read",
					"message": "javax.persistence.OptimisticLockException: Exception [EclipseLink-5011] (Eclipse Persistence Services - 2.6.4.qualifier): org.eclipse.persistence.exceptions.OptimisticLockException\r\nException Description: One or more objects cannot be updated because it has changed or been deleted since it was last read"
				}
			]
		}
	]
}

**Comment by git-jarle** [comment]
This issue can be circumvented by serializing all calls to WegasScript.remoteEval or by gathering all property updates into a single WegasScript.remoteEval.

**Comment by maxencelaurent** [comment]
C'est le comportement voulu.
C'est ce qui arrive quand on met à jour la même variable deux fois en même temps.
