### ISSUE TITLE
Lien sur partie => login as guest

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1331]
par défaut l'url ne devrait pas créer un compte guest.

Trouver une solution pour flexitests.

Sinon il y a qques profs qui donnent le lien aux étudiants:
![capture d ecran 2017-09-19 a 11 57 43](https://user-images.githubusercontent.com/1556490/30587069-30b2bacc-9d32-11e7-93b8-1d2da45f0a1a.png)

**Comment by maxencelaurent** [comment]
TODO: 
GameModelProperties: + Boolean guestAllowed


lobby : autologin.js:56 -> si guestAllowed, LoginAsGuest, sinon, sign up ou log in)
