### ISSUE TITLE
unexpected error "not access rights…" 

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1336]
unexpected error "no access rights…"  (truc du style)

Durant la partie dmp17, c'est arrivé à plusieurs participants et j'ai dû plusieurs fois utiliser => bouton magique => recover rights.

Mais pour d'autres formateurs, ça aurait bloqué le cours...

**Comment by maxencelaurent** [comment]
seems to be related to Permission.equals method.

Seems solved but may required more tests

**Comment by maxencelaurent** [comment]
fix mis en ligne le 25/9/17, 15h

Puisque difficilement reproductible en local, je laisse l'issue ouverte et on verra d'ici quelques jours si le problème est résolu

**Comment by maxencelaurent** [comment]
au 3.10.17, pas de reproduction
