### ISSUE TITLE
Form2 : save number

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1344]
Je clique sur save, mais ça ne crée pas la variable. Il ne se passe rien.

En rafraichissant la page, on voit qu'elle avait été créee, mais pas affichée.

<img width="767" alt="capture d ecran 2017-11-22 a 10 09 13" src="https://user-images.githubusercontent.com/1556490/33118851-6c507f84-cf6d-11e7-8430-cbb16f98e09e.png">

**Comment by CiGit** [comment]
Vérifier quand ce n'est **pas** à la racine
