### ISSUE TITLE
Editor tabs

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1353]
From:
![image](https://user-images.githubusercontent.com/6583528/36018284-7a3a91ce-0d7b-11e8-8764-5aa71f7737c3.png)
close preview tab:
![image](https://user-images.githubusercontent.com/6583528/36018315-9894fe7a-0d7b-11e8-8379-ba1614a3a214.png)
then close the tab container:
![image](https://user-images.githubusercontent.com/6583528/36018339-b8023138-0d7b-11e8-9661-5954171294b3.png)

No way to restore the preview:
![image](https://user-images.githubusercontent.com/6583528/36018378-d7f2978a-0d7b-11e8-953a-598cd51dd370.png)

(switching attrs tab to the right/left eventually restore the preview tab :-/)

**Comment by git-jarle** [comment]
Fixed c4938171cd720e1bf0653e314b9d3dd69be95395
