### ISSUE TITLE
Edition des pages : do not save / keep editing

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1358]
1. créer une page
1.  y ajouter un box
1. sauver la box
1. dans le page treeview, select la page
1. dans le page treeview, select la box
-> le message unsaved change apparaît

**Comment by maxencelaurent** [comment]
entity.get("children").length !== entity.toObject().children.length

**Comment by CiGit** [comment]
>entity.get("children").length !== entity.toObject().children.length

Dans quel cas, parce que c'est étonnant...

**Comment by maxencelaurent** [comment]
Ajoute n'importe quoi dans une page et met un breakpoint sur wegas-editor-entity-action.js:349 (EditEntityAction.currentEntity = entity;

select la page dans le tree view: entity.get("children").length != entity.size(),

**Comment by maxencelaurent** [comment]
On dirait que PageCache.patch ne met pas à jour le cache

**Comment by maxencelaurent** [comment]
(oups)

**Comment by CiGit** [comment]
J'ai un patch qui va arriver. Juste quelques vérifications à faire.

l'ATTRS _children_ est particulier: la mécanique parent-child accept _children_ comme initial setter mais tout se passe ensuite entre `add` et `item`

J'ai pour le moment fait en sort que `get('children')` retourne les enfants actuels et non pas les enfants initiaux.

**Comment by maxencelaurent** [comment]
j'ai aussi un fix mais en forçant le pageloader à recharger la nouvelle page

**Comment by CiGit** [comment]
Tricheur :-)
