### ISSUE TITLE
Page tree view

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1359]
plus de clic droit dans le pageTV ?

**Comment by CiGit** [comment]
Si je ne m'abuse, il y a longtemps qu'il a disparut.

**Comment by maxencelaurent** [comment]
just quoting wegas-editor-pagetreeview.js PageTreeview#renderUI: 
```
if (DATASOURCE.editable) {
    this.plug(PageTreeviewToolbarMenu);
    // @TODO Reactivate this once the new editor FORM2 is ready for production
    //this.plug(PageTreeViewContextMenu);
}
```

**Comment by maxencelaurent** [comment]
Still need some work:
![image](https://user-images.githubusercontent.com/6583528/37270819-923cbfb4-25d0-11e8-9943-6a0089357b37.png)
