### ISSUE TITLE
Scénariste - full screen

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1362]
Dans la nouvelle version du full screen, la barre du haut prend trop de place et il y a plusieurs jeu où on n'arrive plus à voir toute la hauteur de l'écran de jeu.

Solution:  diminuer au max la barre du haut, en gardant jute la place pour les boutons (full screen, reinitialize)

<img width="1284" alt="capture d ecran 2018-03-24 a 09 01 50" src="https://user-images.githubusercontent.com/1556490/37861823-186edc3c-2f42-11e8-8150-8a3460d62b1b.png">

**Comment by CiGit** [comment]
La correction bloque les boutons du haut (restart / logout) d'être cliqué. Avoir accès à ces boutons (surtout restart) en mode fullscreen était la raison de ne pas être en fullscreen réellement.
