### ISSUE TITLE
Module statistique: on ne voit plus les noms de cours

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1363]
Juste les no... 
=> plus utilisable
<img width="543" alt="capture d ecran 2018-03-24 a 09 29 19" src="https://user-images.githubusercontent.com/1556490/37861968-ebbaf58c-2f45-11e8-84e5-9575bf6ef5aa.png">

**Comment by CiGit** [comment]
Il faut être patient. Je viens d'essayer, il faut du temps pour que l'application télécharge les informations.
Sur 2 testes:
- 40 sec
- 20 sec

Ce qui peut être fait:
- indicateur de chargement
- Ne pas télécharger l'ensemble des parties, il me semble qu'il n'y a pas 1493 parties avec `PMG Artos - v1` comme logId ...
