### ISSUE TITLE
Erreurs sur partie PMG demoWebSite EN (9392122)

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1370]
Me met des erreurs si j'essaye de mettre le jeu en individuel ou de le mettre en archives (message erreur dans rectangle rouge)

**Comment by maxencelaurent** [comment]
y avait un machin bizarre au niveau des serveurs, j'ai redémarrer et c'est maintenant ok.

Reste à savoir ce qu'il s'est passé...

**Comment by maxencelaurent** [comment]
ce que je vois dans les logs, c'est que tu étais connecté en guest au moment de faire ça. La vrai erreur qu'on aurait dû t'afficher serait qqch du genre "Access denied"

**Comment by djaccard** [comment]
j'ai aussi eu un access denied
