### ISSUE TITLE
Erreur à l'ouverture PMG démo website 

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1371]
Sur Firefox:
La démo FR fonctionne,
Erreur à l'ouverture démo EN (unexpected null)

Sur chrome:
FR : reste bloquée sur logo Wegas => rafraichir page => OK
EN: ok

<img width="735" alt="capture d ecran 2018-04-04 a 06 29 35" src="https://user-images.githubusercontent.com/1556490/38288533-ad6d8d8c-37d1-11e8-8c0c-ea57e00b3f92.png">

**Comment by maxencelaurent** [comment]
pas là peine de t'amuser avec plein de navigateur, c'est des erreurs côté serveurs qui arrivent de manière aléatoire. Par exemple, j'ai eu:

Firefox + demo FR : gameController injection et OK après refresh
Firefox + demo EN: ok

Chrome + demo FR: ok
Chrome + deom EN: unexpected num et ok après refresh

**Comment by maxencelaurent** [comment]
pour l'instant je comprends rien à ce qu'il se passe. On enlève les liens demo pour le moment ?
