### ISSUE TITLE
form2: MCQ

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1373]
Lorsqu'on a un ChoiceDescriptor dans le formulaire, on ne peut pas passer directement à un autre type d'object, ça ouvre un formulaire vide avec ça dans la console:

```
react-dom.production.min.js:150 TypeError: Cannot read property 'map' of undefined
    at ae (entityarrayfieldselect.js:25)
```

ça fonctionne correctement d'un ChoiceDescriptor vers un SingleResultChoiceDescriptor. Tout le reste à l'air de coincer.

**Comment by CiGit** [comment]
Fixed in 178fbab6083dd59d5191cf58ba5b48594fe9e0e5
