### ISSUE TITLE
Docker logs

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1374]
logrotate + size limit

**Comment by maxencelaurent** [comment]
config mise à jour, besoin de restart docker + destroy container

**Comment by CiGit** [comment]
On peut en profiter pour mettre à jour les serveurs.
rancher en version 1.6.17 (et serveur à jour) :arrow_right: ne supporte pas docker 17.05 (qui est sur la majorité de nos serveurs...)
Il faut encore mettre à jour l'infrastructure https://rancher.com/docs/rancher/v1.6/en/upgrading/#infrastructure-services
