### ISSUE TITLE
Problème à la création des équipes

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1378]
tourne en rond lorsque j'essaye de créer une équipe

<img width="1105" alt="capture d ecran 2018-05-22 a 08 09 50" src="https://user-images.githubusercontent.com/1556490/40345015-ae5a5a86-5d97-11e8-8c2b-8ef991f0ebf0.png">

**Comment by git-jarle** [comment]
Peux-tu réessayer? Chez moi il n’y a aucun problème. Testé avec deux scénarios différents.

-Jarle

**Comment by maxencelaurent** [comment]
pareil pour moi, je peux créer des équipes dans testddd et dans cas182 sans problème
