### ISSUE TITLE
Edition textes dans scénariste

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1379]
QUand j'édite un texte j'ai tout à coup le curseur qui passe tout seul au début du texte

**Comment by maxencelaurent** [comment]
contexte ?  formulaire, table de traductions, édition inline des traduction, champs imput  type avis eval croisées ?

**Comment by djaccard** [comment]
;-) j'avais pas le temps pour la description complète avant le début du cours...

- formulaire scénariste
- description réponse à question
- je veux remplacer time budget par budget temps
je commence à éditer => curseur passe au début du champ texte
<img width="968" alt="capture d ecran 2018-05-25 a 13 54 10" src="https://user-images.githubusercontent.com/1556490/40543132-51086d08-6023-11e8-96b6-112982d33f70.png">

**Comment by djaccard** [comment]
chrome

**Comment by djaccard** [comment]
aussi dans firefox...

**Comment by git-jarle** [comment]
Même problème avec l'édition de texte dans les dialogues, les transitions.
