### ISSUE TITLE
Option mise en forme dans traduction

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1380]
Dans onglet traduction, possible de faire les options de mise en forme "attachées" au dessus du champs, comme dans le formulaire.
Actuellement, elles sont en fixe sur la page, mais quand on scroll, on ne voit plus les textes

<img width="443" alt="capture d ecran 2018-05-25 a 15 14 11" src="https://user-images.githubusercontent.com/1556490/40546101-89e1a99a-602e-11e8-9939-8734ec6f6d52.png">

**Comment by maxencelaurent** [comment]
limite impossible, il faudrait initialiser un éditeur pour chaque traductions. ça serait tellement lourd qu'on n'arriverait même pas à scroller dans la page.

En attendant une vraie solution, si tu re-clique dans le texte, ça repositionne la toolbar au dessus ...

**Comment by djaccard** [comment]
ah...
Ce qui est aussi ennuyant, c'est qu'on ne voit plus le titre de ce qu'on édite.
Dans les fausses bonnes idées:
- le mettre en haut de la page pour tous les champs ?
- ne pas le mettre => on met en forme seulement dans le formulaire (pratique pour le ctrl c ctrl v, mais pas si on fait une vraie traduction manuelle)
- mettre une case à cocher pour activer/désactiver l'affichage de la barre de mise en forme
- laisser comme maintenant

<img width="424" alt="capture d ecran 2018-05-25 a 15 32 03" src="https://user-images.githubusercontent.com/1556490/40546919-d79f6a26-6030-11e8-8b7f-4851100708b0.png">

**Comment by maxencelaurent** [comment]
il y a evt une autre option mais qui a aussi des inconvénients, c'est de faire comme dans les labels : la toolbar ne s'affiche que lorsque du texte est sélectionner

+ c'est bien pour mettre en gras, souligner
- c'est pas pratique pour insérer des images

**Comment by CiGit** [comment]
Solution plus difficile à mettre en place:
Virtualisation -- les champs se rendent comme dans le formulaire, mais uniquement lorsqu'ils sont dans le **viewport** ou _presque_ dedans
