### ISSUE TITLE
PMG : pastille nbre questions non répondues gicle au resize

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1382]
<img width="729" alt="capture d ecran 2018-05-26 a 13 17 01" src="https://user-images.githubusercontent.com/1556490/40575545-2e6a8b5e-60e7-11e8-81b0-ec0f9fa6d578.png">

**Comment by maxencelaurent** [comment]
j'arrive pas à reproduire, quelle navigateur ?

**Comment by maxencelaurent** [comment]
ok, j'arrive à reproduire
