### ISSUE TITLE
problème  l'ouverture du média serious game

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1386]
<img width="1337" alt="capture d ecran 2018-06-18 a 17 17 53" src="https://user-images.githubusercontent.com/1556490/41545521-ad19ec92-731b-11e8-8b35-f04ac71f1f6e.png">

**Comment by maxencelaurent** [comment]
State machine "Avancement des phases", transition de "4 Short List" à "5.1 Réalisation 1", la variable phase courante prend la valeur de 20. 

Cette valeur est ensuite utilisé pour accéder au 20ème élément du dossier "Current periods PMG", quoi n'existe pas : KABOUM !

Solution pour que l'erreur soit plus compréhensible : borner la variable "phase courante" au nombre de phases effectivement défini dans le jeu. Comme ça, on dira que 20 n'est pas un numéro de phase admissible à la place du gros message d'erreur
