### ISSUE TITLE
condition sur boolean: pas wysiwyg

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1388]
il faut aller éditer le script pour mettre true/false
<img width="489" alt="capture d ecran 2018-06-19 a 07 30 57" src="https://user-images.githubusercontent.com/1556490/41578471-d047fce6-7392-11e8-872d-5890feef2fe5.png">

**Comment by CiGit** [comment]
Ce n'est plus le cas. Il y a une _checkbox_ visible.
