### ISSUE TITLE
State machines pas synchronisées (au restart)

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1390]
Dans le preview

**Comment by CiGit** [comment]
Il semble qu'il faut un _gros_ restart.

**Comment by maxencelaurent** [comment]
je ne suis pas sur de comprendre la question de dom, ni la réponse de cyril (on peu faire des _petits_ restart ?).

Si j'ai une state machine:
state1 -> transition sans condition -> state2 sendMail

J'ai bien reçu mon mail après un restart.

Est-ce que ce que tu attend c'est que l'impact qui se situe dans l'état initial soit exécuté lors du restart ?

**Comment by IamFonky** [comment]
Je clean les issues et comme celle-ci n'as pas eu de réponse depuis plus d'une année j'imagine qu'elle est résolue.
