### ISSUE TITLE
Scénariste Full screen: boutons plus actifs

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1392]
En full screen, les boutons Fullscreen, Refresh et Edit page ne foncitonnent plus.
Rienne se passe quand on passe dessus avec la souris.
Chrome

<img width="1047" alt="capture d ecran 2018-07-02 a 12 23 14" src="https://user-images.githubusercontent.com/1556490/42159113-ea6e44b2-7df2-11e8-84fb-c3a80aa14695.png">

**Comment by maxencelaurent** [comment]
corrigé dans les modèles, on attend
