### ISSUE TITLE
lobby trainer: search

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1393]
Si on tape quelque dans le search pendant le chargement des parties, aucune partie ne s'affiche (même s'il y en a qui correspondent aux critères de recherche).

<img width="920" alt="capture d ecran 2018-07-03 a 06 13 36" src="https://user-images.githubusercontent.com/1556490/42198495-84926326-7e88-11e8-82c9-639310855f60.png">

**Comment by maxencelaurent** [comment]
quick fix: wait the list to show search field
