### ISSUE TITLE
Mise en forme texte descriptif question

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1394]
La couleur des caractères (budget temps en vert) n'est pas prise en compte à l'affichage.
Seulement pour ce jeu ?
<img width="965" alt="capture d ecran 2018-07-06 a 14 06 52" src="https://user-images.githubusercontent.com/1556490/42378009-fcb2ff4c-8125-11e8-9ea6-5e6664808b0f.png">

**Comment by maxencelaurent** [comment]
dans wegas-media-basic.css il y a des règles qui forces la couleur : 
```
.yui3-skin-sam .sousPage .wegas-mcqview-content:not(.cbx) .wegas-mcqchoice .mcqchoice__submit span,
.yui3-skin-sam .sousPage .wegas-mcqtabview .horizontal-tabview div.yui3-tabview-panel .wegas-whview .wegas-whview--submit-button {
    background: #4e6eef;
    color: white !important;
}

.yui3-skin-sam .sousPage .wegas-mcqview-content:not(.cbx) .wegas-mcqchoice .mcqchoice__submit span:hover,
.yui3-skin-sam .sousPage .wegas-mcqtabview .horizontal-tabview div.yui3-tabview-panel .wegas-whview .wegas-whview--submit-button:hover {
    background: #2947bc;
    color: #ffe !important;
}

.yui3-skin-sam .sousPage .wegas-mcqtabview .horizontal-tabview div.yui3-tabview-panel .wegas-whview .wegas-boxes-number-input .boxes .box .value {
    color: white !important;
}

.yui3-skin-sam .sousPage .wegas-mcqview .wegas-mcqview-content {
    background: #e4e5e9;
}

.yui3-skin-sam .sousPage .wegas-inbox *,
.yui3-skin-sam .sousPage .horizontal-tabview .yui3-tab a.yui3-tab-label,
.yui3-skin-sam .sousPage .wegas-mcqtabview .horizontal-tabview div.yui3-tabview-panel * {
    color: #666 !important;
}
```

Il faut enlever les "!important" et plutôt ajouter une classe au sélecteur.

**Comment by git-jarle** [comment]
Oui, j’ai rédigé des règles CSS un peu brutales pour rapidement obtenir un résultat homogène pour le test de mercredi passé.
Mis à part cela, je pense qu’il faudrait ajouter un champ texte aux questions qui serait dédié aux informations fournies « hors jeu », telles que budget temps et argent, conseils de jeu pour la suite. On voit qu’on a souvent besoin de ce type d’informations et qu’il faut le présenter différemment, p.ex. dans une fonte spéciale ou dans une bulle d’informations.

-Jarle
