### ISSUE TITLE
access key => partie disparait

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1400]
quand on active désactive la clé dans l'interface trainer, la partie disparait de la liste des parties.
Elle réapparait quand on rafraichit la page

**Comment by djaccard** [comment]
meme chose quand on change la clé

**Comment by maxencelaurent** [comment]
j'arrive pas à reproduire...

**Comment by maxencelaurent** [comment]
comment tu fais exactement ? quel navigateur ?

**Comment by djaccard** [comment]
ça fait ça chez moi et chez les autres => pas lié aux droits admin...
chrome

**Comment by djaccard** [comment]
avant
<img width="1055" alt="capture d ecran 2018-09-03 a 16 34 03" src="https://user-images.githubusercontent.com/1556490/44992318-32159d80-af97-11e8-8d22-fa15ffcf89aa.png">

**Comment by djaccard** [comment]
et on arrive plus à reproduire !!!

**Comment by djaccard** [comment]
mais ça nous a fait ça pendant tout l'après-midi ...

**Comment by maxencelaurent** [comment]
je ne vois rien non plus dans les logs

**Comment by djaccard** [comment]
Reproduction aléatoire ce matin, avec sur une partie fermé clé, sur une autre modifier commentaire
=> partie disparait de la liste.
Pas réussi à faire une reproduction déterministe
