### ISSUE TITLE
PMG - mise en page Lien sur pdf

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1402]
Quand on scrolle la liste des questions, le bouton "pdf" se déplace au lieu de rester en base de la page.

<img width="1053" alt="capture d ecran 2018-09-04 a 11 34 55" src="https://user-images.githubusercontent.com/1556490/45023381-9fc4d680-b036-11e8-80b1-679caec60629.png">

**Comment by maxencelaurent** [comment]
closed by Heigvd/WegasPrivate@649b505
