### ISSUE TITLE
accès jeu

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1411]
je sais pas si c'est grae, mais dans domplayer, j'ai toujours cette partie qui tourne sans arriver à accéder (partie créée hier).

![capture d ecran 2018-10-02 a 08 48 17](https://user-images.githubusercontent.com/1556490/46333392-8e182400-c620-11e8-89fa-0192f2335001.png)

**Comment by maxencelaurent** [comment]
non c'est pas normal, je regarde ça

**Comment by maxencelaurent** [comment]
il y a eu un truc bizarre sur le serveur et ça a bloqué la création de ton player.

Le problème initial semble avoir été créé par une affectation de ressource par un norvégien...

Ce n'est pas lié a m-benefits
