### ISSUE TITLE
Saut de ligne dans éditeur

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1415]
Parfois, quand on élargi la taille de la fenêtre, le texte ne s'affiche pas jusqu'au bout des lignes. On pourrait penser qu'il y a des retours  la ligne.

![capture d ecran 2018-10-16 a 14 42 02](https://user-images.githubusercontent.com/1556490/47017170-e20f2680-d151-11e8-819d-136a2ecb1e77.png)

**Comment by maxencelaurent** [comment]
c'est parce que ce qu'il y a effectivement des retours à la ligne (probablement issus d'un copier-coller). 

Tu sais d’où à été copié ce texte ? C'est vieux non ? ça vient de l'export PDF de l'ancien PMG ?

**Comment by maxencelaurent** [comment]
c'est parce que ce qu'il y a effectivement des retours à la ligne (probablement issus d'un copier-coller). 

Tu sais d’où à été copié ce texte ? C'est vieux non ? ça vient de l'export PDF de l'ancien PMG ?

**Comment by maxencelaurent** [comment]
fixed by 1a9fc1ec2b58aca7490232a98fe5dada25ab9292
