### ISSUE TITLE
Trainer impacts manuels ne fonctionnent plus

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1437]
Clic sur "apply impact" => il ne se passe rien
<img width="867" alt="Capture d’écran 2019-03-14 à 06 27 48" src="https://user-images.githubusercontent.com/1556490/54333337-693dc900-4622-11e9-9839-fb2404563ff8.png">

**Comment by CiGit** [comment]
Mais au moins il est joli :smile:
