### ISSUE TITLE
Edition page: Choix dossier question fonctionne plus

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1447]
On n'arrive pas choisir le Question folder.
Reproduction:
- Edition page
- add => variable = Question folder
- choisir un dossier

**Comment by maxencelaurent** [comment]
moi si

**Comment by maxencelaurent** [comment]
plus de détails ?

**Comment by djaccard** [comment]
t'es trop fort !
essaye dans le jeu DevPro_Base,page options, afficher le dossier des questions "options"
