### ISSUE TITLE
Result conditionnel fantôme

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1497]
Scénario Innocom.
Action Identifier tâches

J'ai créé un conditionnal result, puis (mais pas sûr), j'ai dû supprimer son tag ou faire autre chose que je ne me rappelle plus.
Le result n'est plus visible dans la liste des results, mais apparait encore dans les impacts possibles.
<img width="672" alt="Capture d’écran 2019-11-08 à 08 06 44" src="https://user-images.githubusercontent.com/1556490/68456746-f3b0e980-01fe-11ea-8a99-1228d7f326bb.png">

**Comment by maxencelaurent** [comment]
ah oui, ça c'est bizarre...

**Comment by maxencelaurent** [comment]
Dans l'export PDF il est aussi présent. Je pense que c'est le treeview qui est stupide

**Comment by maxencelaurent** [comment]
bouton magique...

**Comment by maxencelaurent** [comment]
Dans le tree view des variables, les entrées qui commencent pas un underscore sont cachées. Il faut passé en mode avancé pour les voir.

Depuis que tu a enlevé le tag du choice, puisqu'il n'a pas de label non plus, c'est le scriptalias qui est affiché dans le treeview. Celui-ci commence par un underscore -> la variable est cachée

C'est sournois.

Je ne sais pas vraiment ce qu'est la bonne solution à ce problème...

**Comment by djaccard** [comment]
ben pas de bonne solution. est-ce que c'est obligé que le scriptalias commence avec un _ ?
ça devrait être corrigé dans la version react/modèle ?

**Comment by maxencelaurent** [comment]
je sais pas si c'est encore obligé. C'est pour éviter que le scriptalias commence par un chiffre.

A vérifier
