### ISSUE TITLE
Trainer: édition de la clé

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1502]
QUand on clique sur la clé, on dirait qu'on entre en mode édition. mais on ne peut pas éditer.
=> soit ne pas passer en mode édition
=> soit permettre l'édition de la clé sans passer par les paramètres de la partie. ça pourrait être pratique.
<img width="276" alt="Capture d’écran 2019-12-01 à 11 16 46" src="https://user-images.githubusercontent.com/1556490/69912634-4495b580-142c-11ea-8ccd-9a8567c86aee.png">

**Comment by git-jarle** [comment]
Fixed
