### ISSUE TITLE
Mise en forme des réponses aux questions

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1504]
Lorsqu'on a un écran ou projecteur avec une petite définition, on a une mise en page des réponses aux questions qui est peu lisible.
Il faudrait peut-être mettre à la ligne après le titre "Résultat" et indenter moins.

![Capture d’écran 2019-12-02 à 14 09 15](https://user-images.githubusercontent.com/1556490/69962754-fad1cb80-150e-11ea-9bed-c07071f52309.png)

<img width="791" alt="Capture d’écran 2019-12-02 à 14 19 33" src="https://user-images.githubusercontent.com/1556490/69962676-c78f3c80-150e-11ea-84c4-ef80b7b283ce.png">

**Comment by maxencelaurent** [comment]
On a un peu réduit les marges depuis le temps, on peut fermer ?

**Comment by djaccard** [comment]
oui, on peut fermer
