### ISSUE TITLE
Dashboard trainer: fail to render

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1507]
Sur mon vieux mac, chrome Version 49.0.2623.112 (64-bit), si j'ouvre le dshboard trainer, j'ai Failed to render Object.values is not a function.
ça fonctionne sur mon moins vieux mac.

**Comment by IamFonky** [comment]
En effet, Object.value n'est utilisable que sur les navigateurs suivants =>

![image](https://user-images.githubusercontent.com/25899984/71193522-8aef6f00-228a-11ea-95ff-7c1906c9e01b.png)

Si tu utilise un safari plus petit que 10.1, soit un OS X 10.9 Mavericks (2013–2016)  ou plus vieux, tu ne pourra pas utiliser cette méthode.

**Comment by maxencelaurent** [comment]
On peut contourner le problème pour le dashboard, mais il y a probablement d'autres choses qui ne fonctionneront pas ailleurs..
