### ISSUE TITLE
Scénarist -  text editor - view source code

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1515]
Ne fonctionne plus : source code vide
alors qu'il y a du texte en mode wysiwyg

<img width="741" alt="Capture d’écran 2020-02-06 à 10 38 29" src="https://user-images.githubusercontent.com/1556490/73924569-ff2eb200-48cc-11ea-924b-3ffdeb6f51cb.png">

**Comment by maxencelaurent** [comment]
L'éditeur semble avoir crashé...
Normalement, le footer avec le bouton Cancel ressemble à ça:
![image](https://user-images.githubusercontent.com/6583528/76861619-2928ac00-685d-11ea-9a42-f39898f7e70c.png)

Depuis un textDescriptor, j'arrive à passer en mode source sans problème.

Est-ce que quelqu’un arrive à reproduire le bug ?

**Comment by git-jarle** [comment]
Je n’ai pas pu reproduire le bug ni sur Windows (Chrome et Firefox) ni sur Mac (Safari, Chrome et Firefox).
