### ISSUE TITLE
Site web : news pas affichées correctement sur téléphone

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1517]
La lecture des news est pas bien formatée pour téléphone.
Idée solution: mettre image en dessus du texte ou enlever l'image.
![Capture d’écran 2020-02-09 à 18 59 29](https://user-images.githubusercontent.com/1556490/74107267-530bf600-4b6e-11ea-97bb-0a8492c7ac96.png)

**Comment by git-jarle** [comment]
Fixed. Le style de la home page le faisait déjà, mais n'avait pas été entièrement répercuté sur la page dédiée aux News.
