### ISSUE TITLE
Website: Photos sur pages person

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1518]
Je dois donner un lien sur ma page perso pour qu'une journaliste puisse me reconnaitre au rendez-vous au restaurant.
=> j'ai mis à jour ma photo ;-)
=> il faudrait mettre les photos en plus grand, style : https://be.mit.edu/directory/eric-alm

**Comment by djaccard** [comment]
En attendant, j'ai ajouté manuellement une photo plus grande dans le texte.
ça suffira pour aujourd'hui et on pourra améliorer la mise en page à l'occasion.

**Comment by git-jarle** [comment]
Fixed
