### ISSUE TITLE
Edition les impacts/conditions en mode source

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1521]
ça crash quand on essaie de passer un script en vue "source".

Step to reproduce:
Ouvrir n'importe quelle scénario "YUI", par exemple: https://wegas.albasim.ch/edit.html?gameModelId=23951
Aller sur n'importe quel impact:
![image](https://user-images.githubusercontent.com/6583528/75057201-c996e500-54d8-11ea-863d-e67b6037d410.png)

Passer en mode source:
![image](https://user-images.githubusercontent.com/6583528/75056746-e67ee880-54d7-11ea-8a7a-a085b58801a2.png)

**Comment by IamFonky** [comment]
Yes je fais ça ce soir ;)

**Comment by IamFonky** [comment]
Ok, c'est un satané bug qui est toujours en cours dans react-ace, je downgrade le module à la version d'avant...

https://github.com/securingsincity/react-ace/issues/230

**Comment by IamFonky** [comment]
Le boulet, j'ai oublié d'enlever le code commenté, ça sera fait dans mon prochain commit :disappointed:
