### ISSUE TITLE
PM Game: descriptif activités plus accessible

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1523]
Agile Artos, onglet activité, en mode scénariste preview

On ne peut plus cliquer sur l'activité pour lire son descriptif (le pointeur passe en main, mais pas de pop up au clic)
<img width="535" alt="Capture d’écran 2020-02-27 à 08 29 34" src="https://user-images.githubusercontent.com/1556490/75421791-57d8f400-593b-11ea-89fe-ba2df7a8c37a.png">

**Comment by maxencelaurent** [comment]
ok c'était simplement le model qui n'avait pas été propagé...
