### ISSUE TITLE
State machine: copier/déplacer => se mélange dans l'édition

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1527]
Il faudra que je vous montre en live, ce sera plus simple. 

Mais idée:
- on copie une state machine => dans treeview, on est sélectionné sur la copie (ie on édite la copie)
- on renomme le label => ça renomme bien le label de la copie
- on déplace la copie dans le treeview => dans le treeview, on est toujours sélectionné sur la copie
- on renomme un state de la copie => visuellement, je suis sûr d'éditer la copie, mais ça renomme le state de l'original.

**Comment by maxencelaurent** [comment]
en plus: quand on édite un état ou une transition, la state machine en question doit être sélectionnée dans le treeview
