### ISSUE TITLE
PMG - Messages fin d'activité

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1530]
Issue ou à discuter...
En fin d'activité, on reçoit les mails 
- des ressources qui disent avoir terminé l'activité 
- du suivi de projet avec info que l'activité est terminée. 
Est-ce qu'on enlève du suivi de projet qui est redondant ?

<img width="550" alt="Capture d’écran 2020-03-05 à 09 34 18" src="https://user-images.githubusercontent.com/1556490/75962694-866b4780-5ec4-11ea-9527-8d5973b9dac9.png">

**Comment by djaccard** [comment]
aux tests, je confirme qu'on peut enlever les mails de suivi de projet.

**Comment by maxencelaurent** [comment]
fait dans le modèle
