### ISSUE TITLE
PMG agile : Edition des titres des itérations firefox

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1532]
L'édition du titre de l'itération ne fonctionne pas aur firefox (mac, firefo 73.01)

**Comment by maxencelaurent** [comment]
Chez moi, il n'y a pas de problème, chez dom il ne semble plus il y en avoir

@IamFonky, @git-jarle : est-ce que vous arrivez à tester ça ? 

vous pouvez ouvrir le scénario Agile Artos 3.0 (https://wegas.albasim.ch/edit.html?gameModelId=43403) -> tab «Iterations» et essayez d'éditer les noms des itérations.
