### ISSUE TITLE
pdf scénario: mise en page "send message"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1534]
Quand on génère le pdf du scénario, pour le PMgame send message: les mails sont en html, avec les traductions

<img width="633" alt="Capture d’écran 2020-03-11 à 06 40 06" src="https://user-images.githubusercontent.com/1556490/76386245-44c71a80-6364-11ea-8264-2496a4994f2c.png">

**Comment by maxencelaurent** [comment]
duplicates #1375
