### ISSUE TITLE
Traduction : Aucune donnée à afficher

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1536]
Pas traduit en anglais.

Au passage, est-ce qu'on pourrait remplacer par "pas d'activités identifiées pour le moment" ?. Si pas trop difficile.

<img width="477" alt="Capture d’écran 2020-03-16 à 08 17 26" src="https://user-images.githubusercontent.com/1556490/76731857-a4576880-675e-11ea-9145-4cc201c33487.png">

**Comment by maxencelaurent** [comment]
pour la traduction c'est bon, pour changer le texte aussi. Par contre, le message s'affiche aussi pour les ressources: 
![image](https://user-images.githubusercontent.com/6583528/76737878-da4e1a00-6769-11ea-9e04-481fefd0ee6b.png)

Il faudrait trouver un texte qui va bien pour ce cas aussi. ok pour  "Aucunes ressources disponibles" / "No resources available" ?

**Comment by djaccard** [comment]
oui, si possible
