### ISSUE TITLE
Label budget temps: noir sur noir

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1539]
PMG Artos 3.0 waterfall
Et nombre cartes temps plus alignée par rapport aux autres indicteurs.

<img width="115" alt="Capture d’écran 2020-03-17 à 15 52 54" src="https://user-images.githubusercontent.com/1556490/76868635-7f9ae800-6867-11ea-9543-adc94a911d22.png">

**Comment by maxencelaurent** [comment]
corrigé dans le modèle et propagé dans les scénarios.

Les parties déjà créées ne sont pas corrigés
