### ISSUE TITLE
Alloted => Allocated

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1543]
<img width="258" alt="Capture d’écran 2020-04-05 à 11 41 39" src="https://user-images.githubusercontent.com/1556490/78527252-abf9b280-77dc-11ea-8a74-fcdce13b9983.png">

**Comment by maxencelaurent** [comment]
Anne me confirme qu'en compta, ils utilisent plutôt «allocated», même si «alloted» reste correct.

**Comment by git-jarle** [comment]
Merci pour ton feedback « métier ». Selon Google, les deux expressions sont effectivement admises. J’avais initialement choisi « allotted » pour gagner un peu de place à l’écran ☺
