### ISSUE TITLE
pmg trainer: ouverture jeu joueur en lecture

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1545]
uand on clique sur l'oeil pour ouvrir en lecture, on arrive sur une page avec juste une image du gantt

<img width="993" alt="Capture d’écran 2020-05-04 à 12 42 25" src="https://user-images.githubusercontent.com/1556490/80958195-e61e9a00-8e04-11ea-9929-c7f34a5f0917.png">

**Comment by djaccard** [comment]
dans l'id de la page, il y a un gamelock C'est lié ?

**Comment by djaccard** [comment]
ça fait pas avec toutes les parties. Problème avec la partie Unige - CAS santé G2

![Capture d’écran 2020-05-04 à 12 45 26](https://user-images.githubusercontent.com/1556490/80958392-431a5000-8e05-11ea-89b3-c28ff5421224.png)

**Comment by maxencelaurent** [comment]
corrigé pour CAS Santé, je cherche les autres problèmes

**Comment by maxencelaurent** [comment]
Corriger pour toutes les parties que j'ai trouvées. Si ça se reproduit: 
ouvrir le scénario de la partie avec la baguette magique du dashboard, puis, dans l'onglet Layout, remettre la bonne page par défaut en cliquant sur l'étoile. dans le formulaire de la page.
