### ISSUE TITLE
trainer : edition des clés

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1554]
ce serait cool de pouvoir éditer directement la clé depuis le lobby, surtout que visuellement, on a l'impression qu'on peut éditer

<img width="570" alt="Capture d’écran 2020-06-11 à 12 00 27" src="https://user-images.githubusercontent.com/1556490/84372332-3f83a100-abdb-11ea-927a-71acffd1378e.png">

**Comment by git-jarle** [comment]
Ok, je m’en charge. Mais si on permet d’éditer directement depuis la liste des parties, il y a le risque de modifier accidentellement la clé au moment où on la copie. Ce serait donc prudent de demander une confirmation pour toute modification de la clé. Est-ce que ça te va ?

**Comment by maxencelaurent** [comment]
duplicate #1502

**Comment by djaccard** [comment]
éventuellement, il faudrait voir à l'usage si on risque vraiment de la modifier.
