### ISSUE TITLE
PMG Trainer dashboard : Somme BAC

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1563]
Tous les "Sommes BAC sont à 0 alors qu'il y a des groupes (par exemple le très bon groupe Dom) qui ont entré des BAC.

Partie: https://wegas.albasim.ch/host.html?gameId=18687046

<img width="689" alt="Capture d’écran 2020-06-23 à 14 41 58" src="https://user-images.githubusercontent.com/1556490/85404902-e6fbbe80-b55f-11ea-8b5d-269196a57ebe.png">

**Comment by maxencelaurent** [comment]
La très bonne équipe Dom semble avoir largement sous estimé les coûts :
![image](https://user-images.githubusercontent.com/6583528/85409682-67252280-b566-11ea-9d6e-22dfb8d43f5e.png)

C'était un problème dans le modèle. J'ai corrigé : 
1. le modèle
1. ta partie en cours

Je n'ai pas corrigé pour les parties précédentes créées depuis le modèle. Le problème n'existe pas pour les partie pré-modèle (<3.0)
