### ISSUE TITLE
Problème à la reinitialisation du mot de passe depuis admin

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1564]
J'ai réinitialisé le mot de passe d'une participante qui n'arrivait pas se connecter à "test"
en cliquant sur valider, à l'interface, j'ai vu que le 4 points représentant les 4 lettres de test sont passés à une dizaine de point => on se demande ce qu'il se passe.

La participante n'a pas pu se connecter avec le mot de passe "test"

Elle a ensuite pu se connecter en faisant "mot de passe oublié ?" et en entrant elle même le nouveau mot de passe.

J'ai essayé de réinitialiser le mot de passe de domplayer à "test" et je n'arrive pas me connecter avec ce nouveau mot de passe.

**Comment by git-jarle** [comment]
J’ai eu le même problème sur d’autres sites à cause du navigateur (ou un de ses plugins) qui veut à tout prix remplir avec un mot de passe déjà enregistré.
On voit alors le champ password se remplir mystérieusement.
Pour l’instant, pour contourner le problème, le plus simple est de désactiver au moins temporairement cette fonctionnalité du navigateur.

Malheureusement Safari semble ne pas respecter le standard consistant à mettre l’attribut HTML autocomplete="off" sur les champs de saisie.
Il y a un nouvel attribut autocomplete="new-password" que je ne connaissais pas avant aujourd’hui. Je vais l’implémenter sur Wegas, mais Safari semble ne pas le respecter non plus.
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#Browser_compatibility
