### ISSUE TITLE
Distinguish absolutePath and relativePath for files

### ISSUE THREAD

**Issue by IamFonky** [Heigvd/Wegas#1614]
Now the file browser is returning absolutePath witch look like `/Wegas/rest/GameModel/53/File/read/Patients/0/patiente_portrait.jpg`. 
We have to get rid of the `/Wegas/rest/GameModel/53` and only return `/File/read/Patients/0/patiente_portrait.jpg`.
Then the absolute path have to be dynamicaly created in the component that use files in order to keep links working when exporting/copying scenarios.

**Comment by maxencelaurent** [comment]
see https://github.com/Heigvd/Wegas/blob/0f011f94940eed4063ae48210ce89026f7effeaa/wegas-app/src/main/webapp/wegas-app/js/plugin/wegas-injector.js#L44

**Comment by IamFonky** [comment]
Interessant. Ça pourrait être utile surtout pour des TextDescriptor dans lequel on met des images en effet.
