### ISSUE TITLE
State machine plantent

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1616]
Travail difficile dans la state machine "journée à l'hôpital". scénario prits v4
Plante lorsque copie de transitions, déplacement cases.
J'ai fait plusieurs fois rafraichir la page ou cliquer sur le diaglogue dans treeview pour remettre à zéro, mais problèmes reviennent.
J'essaierai de reproduire devant vous à l'occasion ...
<img width="873" alt="Capture d’écran 2020-11-13 à 15 11 02" src="https://user-images.githubusercontent.com/1556490/99081207-bd047080-25c2-11eb-8d8f-d42ec1d72509.png">

<img width="632" alt="Capture d’écran 2020-11-13 à 15 26 15" src="https://user-images.githubusercontent.com/1556490/99082552-9ba48400-25c4-11eb-8ad4-99a4c3537625.png">

**Comment by maxencelaurent** [comment]
C'est quand la dernière fois que quelqu'un a réussi à dupliquer une transition ou un state ? 
ça doit faire longtemps...

**Comment by IamFonky** [comment]
> C'est quand la dernière fois que quelqu'un a réussi à dupliquer une transition ou un state ?
> ça doit faire longtemps...

Pas sur que j'aie même essayé une fois...
