### ISSUE TITLE
PMG v3.0 Edition budget réalisation

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1641]
Le budget entré en fin de phase d'avant-projet reste éditable lorsqu'on entre en planification (mode regroupé).
Il ne devrait plus être éditable. 
<img width="1136" alt="Capture d’écran 2021-01-19 à 16 14 03" src="https://user-images.githubusercontent.com/1556490/105054014-d4a01f80-5a71-11eb-8339-619a5cf3b077.png">

**Comment by maxencelaurent** [comment]
Corrigé dans le modèle mais y a un bug pour la propagation....
