### ISSUE TITLE
PMG _ Onglet ressources, coûts des heures non travaillées / pourrait travailler

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1642]
Il y a un truc que je ne comprends pas dans la légende. C'est quoi ce coûts des heures non travaillées ? Il me semble qu'on pourrait simplement le retirer ou bien ?

Autre question: le "pourrait travailler" n'est pas lié au mode Agile uniquement ?

<img width="876" alt="Capture d’écran 2021-01-20 à 14 01 44" src="https://user-images.githubusercontent.com/1556490/105178368-34f19880-5b28-11eb-885b-d9b5eb65e5dc.png">

**Comment by maxencelaurent** [comment]
Pourrait travailler, c'est si tu mets ASAP

![image](https://user-images.githubusercontent.com/6583528/105179260-64ed6b80-5b29-11eb-8d55-270a72129dc5.png)

**Comment by maxencelaurent** [comment]
"coûts des heures non-travaillées", c'est un effet de bord de la mise à jour de l'onglet projet. ça devrait être marqué "heures non-travaillées".  On va corriger ce texte.

La légende est là car quand une ressource facture des heures non travaillées, on le montre dans son planning : 
![image](https://user-images.githubusercontent.com/6583528/105179528-bbf34080-5b29-11eb-8d7b-58b8eaaa5302.png)

**Comment by djaccard** [comment]
OK !

Le 20 janv. 2021 à 14:14, maxencelaurent <notifications@github.com<mailto:notifications@github.com>> a écrit :



"coûts des heures non-travaillées", c'est un effet de bord de la mise à jour de l'onglet projet. ça devrait être marqué "heures non-travaillées". On va corriger ce texte.

La légende est là car quand une ressource facture des heures non travaillées, on le montre dans son planning :
[image]<https://user-images.githubusercontent.com/6583528/105179528-bbf34080-5b29-11eb-8d7b-58b8eaaa5302.png>

**Comment by djaccard** [comment]
OK !
T'as le droit de dire que je suis insupportable, mais tu crois qu'on pourrait l'afficher seulement si on a un ASAP activé ?
Si pas possible, pas de soucis


Le 20 janv. 2021 à 14:12, maxencelaurent <notifications@github.com<mailto:notifications@github.com>> a écrit :



Pourrait travailler, c'est si tu mets ASAP

[image]<https://user-images.githubusercontent.com/6583528/105179260-64ed6b80-5b29-11eb-8d55-270a72129dc5.png>

**Comment by maxencelaurent** [comment]
Ça doit pas être bien compliqué. Je regarde plus tard si je m'ennuie
