### ISSUE TITLE
PageEditor Layout

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1649]
Impossible to organize PageEditor panels like 

![image](https://user-images.githubusercontent.com/6583528/105881165-75f41c00-6004-11eb-9bd1-bc7ab39efa6d.png)

**Comment by SandraMonnier** [comment]
I can easily set that organisation. What would you have different ?

<img width="1023" alt="Screenshot 2021-01-27 at 11 41 53" src="https://user-images.githubusercontent.com/70577952/105980045-adaaa480-6094-11eb-9eb5-34ca1bce3abc.png">

**Comment by maxencelaurent** [comment]
So I tried the easy way:


https://user-images.githubusercontent.com/6583528/105987202-3f6adf80-609e-11eb-9246-9757cc362402.mp4

**Comment by IamFonky** [comment]
Je vois ou est le problème.
Je m'en occupe des que j'ai un moment!

**Comment by IamFonky** [comment]
Done since commit 6e34e8fec23f37e7f457e38772d3944348217502
