### ISSUE TITLE
PMG Model : unexpceted error null

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1651]
quand je remets le jeu à zéro.
Dernière action: changé le texte de la variable Agile (mais ça date peut-être d'avant)

<img width="1246" alt="Capture d’écran 2021-01-27 à 14 23 23" src="https://user-images.githubusercontent.com/1556490/105996940-4d732d00-60ab-11eb-8009-0437053a392e.png">

**Comment by maxencelaurent** [comment]
pas vérifié si c'est le même problème, mais je viens de corriger un truc très similiaire.

ça sera corriger avec la mise à jour de demain soir
