### ISSUE TITLE
Stats fonctionnent pas

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1655]
En tout cas pour cette partie: tourne sans s'arrêter

<img width="880" alt="Capture d’écran 2021-02-10 à 09 20 16" src="https://user-images.githubusercontent.com/1556490/107490717-8d95dd80-6b8a-11eb-8bfb-9d626ab7082e.png">

**Comment by maxencelaurent** [comment]
ça marche très bien...
![image](https://user-images.githubusercontent.com/6583528/107514414-eaed5700-6ba9-11eb-9009-abdccf7f157a.png)

(il faut juste attendre quelques minutes pour changer de question...

**Comment by maxencelaurent** [comment]
Je vais regarder ça

**Comment by maxencelaurent** [comment]
Il manquait quelques indes dans mongo. C'est nettement plus rapide maintenant /eg. https://wegas.albasim.ch/host.html?gameId=19188706)

Il y a toujours deux trois problèmes depuis la vue admin par contre...
