### ISSUE TITLE
PRITS Dialogue Editor: plante à ajout Etat

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1663]
J'ai voulu ajouté une transition vers un nouvel état => page blanche.
J'ai dû recharger la page et revenir dans l'onglet PRITS => la transition et le nouvel état avaient bien été créés.

**Comment by IamFonky** [comment]
je vais investiguer ça

**Comment by IamFonky** [comment]
Je n'arrive pas a reproduire le problème. C'était dans quel cas? Quand tu modifies un dialogue?

**Comment by djaccard** [comment]
Chez moi j'arrive reproduire.
juste essayé de créer une nouvelle transition dans le dialogue Alfred accident de moto
