### ISSUE TITLE
PRITS éditeur de texte

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1664]
Modification d'un texte:
- on entre le nouveau texte
- save
- l'ancien texte est affiché. Il faut rafraichir pour voir le nouveau texte
<img width="293" alt="Capture d’écran 2021-03-18 à 13 21 38" src="https://user-images.githubusercontent.com/1556490/111625425-20aade80-87ed-11eb-939e-66e94992d2d8.png">
un peu déroutant

**Comment by IamFonky** [comment]
ça marche c'est juste qu'il faut ~4sec pour mettre a jour... :grin: 
![image](https://user-images.githubusercontent.com/25899984/111631427-aaf64100-87f3-11eb-8ea4-3e8b1f2a2384.png)
Je vais voir ce que je peux faire

**Comment by IamFonky** [comment]
Le temps est le même quand on passe par l'éditeur d'instance

**Comment by IamFonky** [comment]
Je pense que ça a rapport avec le nombre de triggers.
Avec Wegas actuel, modifier une instance :
 - Scénario vide : 250ms
 - Programming game : 1000ms
 - Scénario vide + 5 triggers : 700ms 
 - Scénario vide + 10 triggers : 1100ms
 -  - Scénario vide + 20 triggers : 1700ms

**Comment by IamFonky** [comment]
On est dessus avec @maxencelaurent  ;)
