### ISSUE TITLE
PRITS responsive

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1669]
Les Exercices passent en dessous alors qu'il rest suffisamment de place pour les mettre.
<img width="1153" alt="Capture d’écran 2021-03-22 à 17 03 51" src="https://user-images.githubusercontent.com/1556490/112020611-c71a1b00-8b30-11eb-99f5-86dd179f8e1c.png">

**Comment by IamFonky** [comment]
J'ai enlevé le wrapping... Dis moi si tu préfère mais je peux pas faire vraiment mieux...
