### ISSUE TITLE
Editeur dialogues : cohérence couleurs

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1676]
Je sais que ça risque d'être pour chaque jeu différent et qu'il n'y a peut-être pas de solution.
Mais dans le cas de PRITS, les couleurs sont inversées entre le dialogue à  l'affichage joueur et l'éditeur:
- bleu clair pour ce que dit le patient dans le dialogue affiché
- bleu foncé pour ce que dit le patient dans l'éditeur de dialogue.

On pourrait peut-être proposer au moins dans la version de base une solution cohérente. Ou on peut régler ça avec les thèmes ?

<img width="325" alt="Capture d’écran 2021-04-18 à 09 48 51" src="https://user-images.githubusercontent.com/1556490/115139211-ef624000-a030-11eb-8be3-7401b63d8979.png">

<img width="369" alt="Capture d’écran 2021-04-18 à 10 28 37" src="https://user-images.githubusercontent.com/1556490/115139196-e3767e00-a030-11eb-8cb1-cf15052034d1.png">

**Comment by IamFonky** [comment]
Relié à #1675
