### ISSUE TITLE
Mise à jour des comptes depuis l'admin: collision d'adresse

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1681]
Dans Wegas user, Estelle Prior a l'adresse mail :
Estelle.Prior@unige.ch (je lui l'ai changée)

Et le mot de passe :
achanger (je l'ai aussi changé)

Mais on n'arrive pas se loguer avec cette adresse/mot de passe (message login mot de passe incorrect).

**Comment by maxencelaurent** [comment]
Le vrai problème c'est que depuis l'admin, on arrive à changer l'adresse d'un compte en utilisant une adresse déjà utilisée par un autre compte.

**Comment by maxencelaurent** [comment]
À vérifier si on ne fait pas un test case-sensitive...

**Comment by xgo-work** [comment]
Fixed by #1916
