### ISSUE TITLE
WEGAS REACT: cannot add boolean variable from variables tab

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/Wegas#1688]
Impossible to add boolean variable from tab Variables.

**Comment by IamFonky** [comment]
![image](https://user-images.githubusercontent.com/25899984/119857728-17886d00-bf14-11eb-8041-1ad74d916b30.png)
"Is required" problem i suppose

**Comment by IamFonky** [comment]
JSONInput seem to fail refreshing values that does not contain undefined values...

For entites with unknown parentId, JSONForm infers required values from default values (cahnges are mades as soon as the value is passed in the JSONFrom component):
![image](https://user-images.githubusercontent.com/25899984/119980935-46a6e900-bfbd-11eb-99a5-663efdb00d43.png)


For entities that contains no undefined fields, the inference doesnt work (new fields are not added):
![image](https://user-images.githubusercontent.com/25899984/119981047-748c2d80-bfbd-11eb-9dd5-8c1fc849dab8.png)

**Comment by IamFonky** [comment]
Here is a super ugly workaround

![image](https://user-images.githubusercontent.com/25899984/119983019-e36a8600-bfbf-11eb-8f50-9b5f49f59859.png)
