### ISSUE TITLE
WEGAS REACT: compo properties > condition layout resetting to false when using boolean variable

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/Wegas#1689]
In my case:
- Creating a button, want to set it disabled so:
- condition layout > disabled if
- Using the Select input > Boolean > true
- Then, when saving or editing something else, it switches to false automatically
- Need to go in code to make it work, and even in code box, it switch sometimes to false.

**Comment by IamFonky** [comment]
Duplicate #1617
