### ISSUE TITLE
PMG: mise en page descriptif des activités

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1690]
Quand on met un texte en italique , à l'affichage il est indenté. On peut enlever cette indentation ?

<img width="665" alt="Capture d’écran 2021-05-28 à 14 10 37" src="https://user-images.githubusercontent.com/1556490/119982063-a8b41e00-bfbe-11eb-8f04-21ecf603eba0.png">

**Comment by maxencelaurent** [comment]
Corrigé dans le modèle et dans ta partie du jour
