### ISSUE TITLE
Select comp in Page Layout (page editor), weird modal + impossible to close

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/Wegas#1692]
When selecting a variable or comp in Page Editor > Page Layout:

- Modal with "File not found" opens weirdly (bottom)
- Neither close or back buttons close this modal (only way is to click on another comp in page layout)

**Comment by IamFonky** [comment]
Cannot reproduce.

Sometime a printscreen is worth a thousand words :stuck_out_tongue:

**Comment by audreyhuguenin** [comment]
![Capture](https://user-images.githubusercontent.com/43539287/120308729-b3c7c080-c2d4-11eb-9145-c5a45e644a45.PNG)

- Local (dev)
- Branch: Wegas_new_UI
- Firefox
