### ISSUE TITLE
PRITS question textes libres

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1693]
A l'ouverture de la question: null dans le champ texte
ça plante quand on essaye d'entrer du texte. Le texte qu'on entre s'efface tout seul
<img width="1835" alt="Capture d’écran 2021-06-02 à 15 02 20" src="https://user-images.githubusercontent.com/1556490/120484621-8b62c380-c3b3-11eb-9943-0c610ae66cda.png">

**Comment by IamFonky** [comment]
Je tente de le reproduire mais je n'y arrive pas pour le moment...
