### ISSUE TITLE
Scénariste: Edition textes plus possible

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1730]
Je n'arrive pas éditer les champs textes. Curseur qui revient au début de la ligne quand on commence à taper.

<img width="776" alt="Capture d’écran 2021-08-09 à 11 25 04" src="https://user-images.githubusercontent.com/1556490/128685543-139d48c4-1795-4b0a-b1c0-fdfa7c29da1c.png">

**Comment by IamFonky** [comment]
Marrant. ça fait pas sur tous les scénarios PMG.

Je crois que je vois pourquoi.

Le sanitizer remplace les caractères spéciaux : `&eacute` devient `é` du coup l'éditeur pense qu'on lui a donné un nouveau texte
