### ISSUE TITLE
TinyMCE textaera not editable after tab repositionning

### ISSUE THREAD

**Issue by IamFonky** [Heigvd/Wegas#1758]

**Comment by xgo-work** [comment]
To reproduce :
- On any page create a text input
=> you can edit text in it
- Move some thumb (for example variable thumb)
=> the text input is "locked" / screwed
=> if some variable update is sent to this corrupted text component, it crashes (in Firefox)

**Comment by xgo-work** [comment]
After discussion with PB, I will try to integrate quill
