### ISSUE TITLE
login wegas: password weak/Ok/weak

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1764]
si on tape
asdfasdfasdfasdfasdf
le password passe de to weak => OK => too weak => OK => ...

**Comment by IamFonky** [comment]
Après discussion, nous pensons que le formulaire mérite un petit redesign pour que les champs faux soient mieux indiqués et que la qualité du mot de passe ne soit pas indiquée (juste ok/pas ok)

**Comment by IamFonky** [comment]
related to #1765
