### ISSUE TITLE
PRITS: feedback réponse aux questions

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1767]
Qunad on clique sur une réponse, il ne se passe rien pendant plusieurs secondes. On a l'impression que le clic n'a pas eu d'effet. 
<img width="954" alt="Capture d’écran 2021-12-17 à 13 02 45" src="https://user-images.githubusercontent.com/1556490/146542326-4142644b-75fc-42b7-ae52-bd3004886d32.png">

**Comment by IamFonky** [comment]
Si jamais, sur le scenario Devpro React il y avait au moins 25 Vignettes en archives et comme on cache le bouton d'archives ben on pouvait pas les voir. Maintenant c'est nettement plus rapide.
J'ai quand même ajouté un loader dans le code qu'on va mettre a jour tout soudain au cas ou ça devait se reproduire.
