### ISSUE TITLE
Password too weak:  message is erroneous

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1769]
![image](https://user-images.githubusercontent.com/6583528/146729478-e6793160-b621-432e-ad89-aa709c7383cf.png)

Some passwords meet the displayed requirements, but are not accepted.
Eg:

- Asdfqwer2

**Comment by IamFonky** [comment]
Faut que se pose la question ensemble de ce champ mot de passe je pense.
L'algorithme de cet input est bien perché et je pense que les utilisateurs ne devraient pas à avoir comprendre celui-ci pour trouver un bon mot-de-passe mais en même temps c'est le meilleur moyen de garantir que le mot de passe ne soit pas trop simple.
Si on garde ce champ tel quel, est-ce qu'on a moyen d'expliquer à l'utilisateur comment faire pour choisir un bon mot de passe (sans lui faire une liste de condition gigantesque)?

**Comment by maxencelaurent** [comment]
La librairie fournit des warnings et des suggestions, à voir si c'est suffisamment clair

On peut tester en live ici: https://lowe.github.io/tryzxcvbn/

![image](https://user-images.githubusercontent.com/6583528/146912205-a08cd901-26b1-4b52-8868-dc0918d99d07.png)

**Comment by audreyhuguenin** [comment]
We should discuss a solution all together before implementing anything different to avoid changing 10 times. I find those suggestions not really clear for common user.

**Comment by IamFonky** [comment]
Alright, let us discuss that at the next weekly meeting.
We'll test it altogether and it shouldn't take more than 5 min to take our decision.

**Comment by xgo-work** [comment]
Has that been fixed or is that still an issue ?

**Comment by xgo-work** [comment]
fixed by #1910
