### ISSUE TITLE
Droit des société: mise en forme des réponses

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1784]
Dans l'historique, on dirait que la réponse choisie par le player (Non, la société ne peut pas ...) fait partie de la description de la question.
Comme s'il manque un titre "Choice" ou "Answer" avant la réponse choisie.
<img width="1102" alt="Capture d’écran 2022-01-25 à 08 46 26" src="https://user-images.githubusercontent.com/1556490/151003501-374366c7-058a-4e99-b123-2ddf7ffbc290.png">

**Comment by maxencelaurent** [comment]
Pas incroyable comme solution, mais ça semble deja mieux 

![image](https://user-images.githubusercontent.com/6583528/151365382-3ffb0623-e72f-40e8-a219-c19a238e377b.png)
