### ISSUE TITLE
Mise en forme CSV de Invoicing

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1787]
Le CSV exporté depuis l'onglet Invoicing a les nombres de players entre guillemets => dans excel, on n'arrive pas faire les sommes.
Une possibilité pour convertir le CSV ou ne pas avoir les guillemets dans le CSV ?
<img width="729" alt="Capture d’écran 2022-02-01 à 16 20 22" src="https://user-images.githubusercontent.com/1556490/151996859-787913ed-ad61-4c26-83f5-96687a419864.png">

**Comment by maxencelaurent** [comment]
je rergade d'ici ce soir

**Comment by djaccard** [comment]
C'est en ligne ? J'ai essayé, mais le CSV est toujours avec les nombres entre guillemets...
