### ISSUE TITLE
React : String variable creation fails after changing from number

### ISSUE THREAD

**Issue by xgo-work** [Heigvd/Wegas#1800]
Steps to reproduce :
- Create a number variable (do not save)
- Create a string variable (when prompted for saving, click do not save)
- ISSUE : the Maximum field still exists (it shouldn't)
- ISSUE : saving doesn't work

PB : likely form scheme doesn't update properly

**Comment by xgo-work** [comment]
have fun

**Comment by IamFonky** [comment]
Maximum field is part of the StringDescriptor schema.
The problem is that it shouldn't be visible while there is no "allowed values".
![image](https://user-images.githubusercontent.com/25899984/156329118-3138afd8-c234-441c-bdfb-b96240c4eb30.png)
