### ISSUE TITLE
StateMachineEditor: state and transition labels

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#1821]
# Current behaviour
display explicit labels if any, “Empty” otherwise.

This is misleading because state and translation labelled with "Empty" may not been empty.

# Expected behaviour

## Transition
* display explicit label, if any
* otherwise, if a condition is defined, display pretty-printed script
* if none: display "empty"

## State
* display explicit label, if any
* otherwise, if an impact is defined, display pretty-printed script
* if none: display "empty"

Hint: have a look on YUI version:

| React | YUI |
| - | - |
| ![image](https://user-images.githubusercontent.com/6583528/163325010-d0206174-269d-41a0-a91f-dfe41022441c.png)      | ![image](https://user-images.githubusercontent.com/6583528/163324714-34a6af4a-06ce-4a21-b870-ebf0bee0572f.png) |

**Comment by xgo-work** [comment]
Work in progress. Transition show logic. hover on transition and states shows logic. See #1872
