### ISSUE TITLE
Lobby admin : something went wrong

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1834]
Message au chargement de la page lobby admin

<img width="1107" alt="Capture d’écran 2022-05-18 à 06 51 19" src="https://user-images.githubusercontent.com/1556490/168959692-31b6d2f1-08fb-4fae-beab-5ab3b484ddfe.png">

**Comment by maxencelaurent** [comment]
ça n'a pas l'air de se reproduire systématiquement.

A quelle heure ça t'est arrivé, que je fouille dans les logs ?

**Comment by djaccard** [comment]
ah non, ça fait plus.

vers les 6h45. J'ai rafraîchi trois fois la page et 3 fois le message. mais ensuite, j'ai pu utiliser wegas. Il n'y avait pas d'autre problème que le message.

A+
Dom

Le 18 mai 2022 à 07:20, maxencelaurent ***@***.******@***.***>> a écrit :



ça n'a pas l'air de se reproduire systématiquement.

A quelle heure ça t'est arrivé, que je fouille dans les logs ?
