### ISSUE TITLE
Fancy icons and illustrations for map components

### ISSUE THREAD

**Issue by IamFonky** [Heigvd/Wegas#1836]
Illustrations for componentPalette
![image](https://user-images.githubusercontent.com/25899984/169511200-98c70648-dd2f-4508-b2cb-b6564a8455f2.png)

Icons for components in pageLayout
![image](https://user-images.githubusercontent.com/25899984/169511293-7f559b1d-f4d2-4c70-9a28-771e4731ad9b.png)

**Comment by IamFonky** [comment]
To do in map-component branch

**Comment by audreyhuguenin** [comment]
Illustrations done and set up. Icons we can leave as it is.
