### ISSUE TITLE
Wegas Admin: Pas possible éditer "comments" d'un utilisateur

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1841]
<img width="987" alt="Capture d’écran 2022-06-07 à 14 49 31" src="https://user-images.githubusercontent.com/1556490/172383391-c23c68c4-1e8f-4f0f-a49f-3ca0efbfe65b.png">

**Comment by maxencelaurent** [comment]
t'es sur que tu peux pas scroll ?

**Comment by djaccard** [comment]
pas de reproduction chez moi non plus...
