### ISSUE TITLE
PMG: bouton "next period"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1842]
Il arrive souvent que des équipes ne comprennent pas qu'il faut cliquer sur "next period". Quand je vois qu'ils restent en période 1  et que je passe vers eux pour leur dire de passer à la période suivante, ils disent "mais on ne veut pas passer en clôture"

Possible de mettre le bouton "next period" à côté des périodes (après la dernière période) ?

<img width="523" alt="Capture d’écran 2022-06-09 à 13 56 44" src="https://user-images.githubusercontent.com/1556490/172841703-0f7287a4-30f0-4272-9b65-e344fb654eef.png">

**Comment by xgo-work** [comment]
Will be done in the React version
