### ISSUE TITLE
Wegas React : éditeur texte plante quand on essaye d'insérer une image

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1862]
Ou peut-être que je ne comprends pas comment il faut faire.

**Comment by xgo-work** [comment]
Je n'arrive pas à reproduire. Tu peux fournir un exemple ?

**Comment by TehAwol** [comment]
J'arrive pas à reproduire non plus. 
J'ai testé les manières suivantes avec des images de plusieurs tailles (dimensions / poids) : 
- Copy & paste d'image clavier (ctrl+c, ctrl+v)
- Copy & paste d'image souris (right click + copy, right click + paste)
- Insérer à travers l'éditeur de texte (puis en uploadant un nouveau fichier ou avec existant)
