### ISSUE TITLE
Toolbar editeur texte React

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#1882]
Est-ce qu'on pourrait la mettre sur une plus grande largeur ?
<img width="700" alt="Capture d’écran 2023-02-06 à 12 49 42" src="https://user-images.githubusercontent.com/1556490/216964253-1b3ad2ac-c971-4d04-94ab-c9b2c993df1d.png">

**Comment by TehAwol** [comment]
Je n'arrive pas a répliquer, t'as plus d'infos (navigateur, comportement) ?

**Comment by xgo-work** [comment]
@TehAwol t'avais fait un fix la-dessus juste ?
