### ISSUE TITLE
Checkbox Question bad request on answer

### ISSUE THREAD

**Issue by xgo-work** [Heigvd/Wegas#1892]
Happens in MIMMS 0.1 in METHANE self evaluation, when clicking on validate

(does not happen in the UnPeuDeReact question tests)

XHRPOSThttps://dev.albasim.ch/rest/Editor/GameModel/1953/VariableDescriptor/QuestionDescriptor/ValidateQuestion/355037/Player/354975
[HTTP/2 400 Bad Request 108ms]

{"@class":"ManagedResponse","deletedEntities":[],"updatedEntities":[],"events":[{"@class":"ExceptionEvent","exceptions":[{"@class":"WegasScriptException","script":"function(e) {\n            \"use strict\";\n            var message = QuestionFacade.buildReplyValidateMessage(self, e, I18n, config || {});\n\n            if (message) {\n                if (typeof inboxNameOrCb === \"function\") {\n                    inboxNameOrCb(message, e);\n                } else {\n                    //sendDatedMessage(self, from, date, subject, body)\n                    Variable.find(gameModel, inboxNameOrCb).sendMessage(self, message);\n                }\n            }\n        }","lineNumber":null,"message":null,"localizedMessage":null}]}]}

**Comment by TehAwol** [comment]
Fixed by @maxencelaurent, related to the games server scripts trying to use unexisting variable (i.e. phaseMSG).
