### ISSUE TITLE
Error 400 when creator of a game tries to add other trainers

### ISSUE THREAD

**Issue by xgo-work** [Heigvd/Wegas#1930]
a user reported that he could not add trainers to one of his games, an error message was shown

Problem is reproducible by impersonating this user
- Impersonate user 42598
- Open the permissions modal of the ***-PSG game
- Click the Trainers tab

=> a 400 error happens on rest call
`rest/User/FindEditorsByInstance/`

 Error

`Subject does not have permission [Game:Edit:g30041738]`

Same goes for all the games for the games of the same user created recently (october 2023)
Could not reproduce the error with older games or with other users.

Permissions on this game for this user are correct.

Surprisingly, the same DB and version WEGAS on another cluster works properly.

**Comment by maxencelaurent** [comment]
fixed (e5d9b4d0c2c1fe04dd5940cd82b395de3d2674a4)
