### ISSUE TITLE
Zone centrale preview: pas possible de la cacher

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#258]
Quand on entre un scénario, parfois on souhaite avoir plusieurs documents à l'écran et réduire la taille de la fenêtre wegas. Ce serait bien de pouvoir fermer la zone centrale. On peut essayer de tricher en la réduisant à zéro, mais après, si on essaie de réduire la fenêtre wegas, on ne voit plus la liste de gauche. Peut-être plus clair sur l'image.

![capture decran 2013-09-09 a 16 36 04](https://f.cloud.github.com/assets/1556490/1107453/724448fa-195d-11e3-8b2e-f470b12ede3c.png)

**Comment by CiGit** [comment]
toujours un problème au redimensionnement de la fenêtre.
Peut être garder les valeurs en pourcentage.
