### ISSUE TITLE
Commenting Impact source

### ISSUE THREAD

**Issue by maxencelaurent** [Heigvd/Wegas#736]
It shall be great to have such a possibility.... For the time, comments are just purged by, I guess, the JS parser.

Example : 
![edition](https://cloud.githubusercontent.com/assets/6583528/3654719/6b20197c-116f-11e4-8f59-2de79bb010e6.png)

Then save close and re-open the impact source editor :
![after](https://cloud.githubusercontent.com/assets/6583528/3654736/bfc1eb90-116f-11e4-9c22-f8fcba365329.png)

**Comment by djaccard** [comment]
on a les cases commentaires => fonctionne comme ça pour le moment, on verra plus tard si à nouveau nécessaire.
