### ISSUE TITLE
Team edition - Unable to remove player

### ISSUE THREAD

**Issue by fxaeberhard** [Heigvd/Wegas#818]
Si on a crée un compte en créant l'équipe, mais qu'on a pas le mot de passe ni d'email, on ne peut pas rajouter la personne.

Rajouter un bouton permettant d'enlever un player d'un équipe

![image](https://cloud.githubusercontent.com/assets/138718/4369957/2ebdb3b6-4303-11e4-9e02-766a19badab0.png)

**Comment by djaccard** [comment]
On peut deleter un joueur tant que pas "sauver". ensuite plus possible.
On laisse comme ça en attendant.
