### ISSUE TITLE
Trainer preview: voir les joueurs

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#847]
On doit aller dans preview pour voir les joueurs de l'équipe. Ce serait bien de pouvoir aussi "ouvrir" l'équipe depuis l'onglet "overview"

![capture d ecran 2014-10-29 a 08 09 58](https://cloud.githubusercontent.com/assets/1556490/4822040/b9a67d34-5f3a-11e4-8b7a-bb764e3db06f.png)

**Comment by CiGit** [comment]
Ongoing work: branch Overview
