### ISSUE TITLE
change not saved

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#871]
Je fais "save" => item updated
je ressors, puis revient et avant de toucher quelque chose, j'ai "change not saved"
a priori, ça ne me fait pas ceci avec d'autres results

![capture d ecran 2014-11-20 a 16 25 22](https://cloud.githubusercontent.com/assets/1556490/5127062/f8e01f16-70d1-11e4-881b-b42f3e81ef34.png)

**Comment by maxencelaurent** [comment]
Toujours le cas ?

**Comment by djaccard** [comment]
je ferme. on réouvrira si ça réapparait
