### ISSUE TITLE
recherche full ne fonctionne pas

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#884]
![capture d ecran 2014-12-17 a 14 41 45](https://cloud.githubusercontent.com/assets/1556490/5471906/e8f9476a-85fa-11e4-9efe-cec40a8dd649.png)

**Comment by maxencelaurent** [comment]
bug avec les caractère spéciaux si la cible de la recherche est formatée en html...

(on recherche "é" mais les "vrai" text est "&eacute;"...)
