### ISSUE TITLE
lobby trainer: mise en page onglets haut

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#892]
Onglet colonne de droite: on ne voit plus les textes en entier (access, details, etc.):

![capture d ecran 2015-01-14 a 10 53 34](https://cloud.githubusercontent.com/assets/1556490/5736906/bfd6d18a-9bdb-11e4-9016-dc4fb09c3d32.png)

**Comment by djaccard** [comment]
idem: on ne peut pas cliquer sur "edit game" depuis trainer/animation partie
Firefox

**Comment by maxencelaurent** [comment]
C'est reglé
