### ISSUE TITLE
trigger: condition sur réponse effectuée

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#904]
on dirait que ce trigger se déclenche lorsqu'on répond à la question 180, quelque soit la réponse. Alors qu'il devrait se déclencher uniquement si réponse b)

![capture d ecran 2015-02-05 a 08 47 36](https://cloud.githubusercontent.com/assets/1556490/6056625/d905f430-ad13-11e4-8566-bb8f32015146.png)

**Comment by maxencelaurent** [comment]
j'ai testé sur une copie du scénarion et le trigger ne se déclanche pas... dur à dire pourquoi le mail est arrivé deux fois...

**Comment by maxencelaurent** [comment]
ok: erreur dans le scénario
