### ISSUE TITLE
PMG Belleville: besoin 0 communication junior

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#906]
Tâche 8, ne devrait pas afficher ce besoin de 0

![capture d ecran 2015-02-05 a 13 43 45](https://cloud.githubusercontent.com/assets/1556490/6060434/2d1b7aa8-ad3d-11e4-9a3e-dd71edfdb522.png)

**Comment by maxencelaurent** [comment]
pas faux... de plus, il faudrait vérifier les calculs quand la quantité <= 0...
