### ISSUE TITLE
Différencier visuellement "Edit scénario" de "edit game"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#907]
ça éviterait les risques d'erreurs. Ici, c'est l'édition d'un game, mais ça crève pas les yeux...

![capture d ecran 2015-02-05 a 14 00 39](https://cloud.githubusercontent.com/assets/1556490/6060631/8daa04aa-ad3f-11e4-8240-0b745a3cb6fd.png)

**Comment by maxencelaurent** [comment]
ça va crever les yeux !
