### ISSUE TITLE
Scénariste: taille des zones de saisie "limite d'avancement"

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#908]
Difficile de voir que si c'est un 10 ou un 100.
On pourrait augmenter la taille (surtout en comparaison avec la ligne de dessous...)

![capture d ecran 2015-02-05 a 14 03 38](https://cloud.githubusercontent.com/assets/1556490/6060663/f18c8434-ad3f-11e4-9aa8-7124ef95f9e2.png)

**Comment by Rapou** [comment]
Même problème que l'issue #939, un paramètre size bloquait la largeur. Le paramètre a été édité pour laisser apparaitre 3 nombres
