### ISSUE TITLE
Introduction BAC: parfois ce qu'on est en train d'entrer disparait

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#912]
je rentre les BAC et parfois ça se remet à 0 => je perds ce que je suis en train de taper. On dirait que ça arrive lorsque:
- on entre une valeur pour une tâche
- tab => tâche suivante où aucune valeur n'a été entrée
- au 2ème chiffre entré, ça s'efface

navigateur: chrome

![capture d ecran 2015-02-05 a 14 19 50](https://cloud.githubusercontent.com/assets/1556490/6060882/82f66a1e-ad42-11e4-89af-6d81507d9f3d.png)

**Comment by maxencelaurent** [comment]
c'est a cause de la synchronisation des widget... On doit faire une synchronisation plus fine, mais c'est pas fait en un coup de cuiller à pot...
