### ISSUE TITLE
search full: ne fonctionne pas avec les accents

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#915]
Il me semble que c'est lié aux accents.
On dirait que ça joue pour les accents dans les titres, mais pas ceux dans les textes de description par exemple des results.

![capture d ecran 2015-02-09 a 08 17 25](https://cloud.githubusercontent.com/assets/1556490/6102308/4e321752-b034-11e4-92fd-3e21f61e452e.png)

**Comment by maxencelaurent** [comment]
Duplicate of #884
