### ISSUE TITLE
search: AND ou OR ?

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#918]
Il me semble qu'on avait dit que le search recherchait les textes correspondant exactement, mais si je fais une recherche avec:
"timeCards").add(self, 500);
j'obtiens: 
![capture d ecran 2015-02-13 a 07 11 26](https://cloud.githubusercontent.com/assets/1556490/6183021/8e96bcda-b34f-11e4-8a5f-e615ae6dc9d0.png)

On dirait que c'est parc qu'il y a un add 500 aux frais fixes. Mais pas exactement ce que je cherchais.

**Comment by CiGit** [comment]
C'est en AND.
MAIS : la recherche est dans ce cas ci sur `"timeCards").add(self` AND `500);` C'est coupé sur les virgule et les espaces. Je vais mettre le comportement que tu attends
