### ISSUE TITLE
lobby trainer: enlever bouton "refresh" de la colonne de gauche

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#923]
Si même fonction que le refresh qui est comme bouton en haut de la colonne droite, l'enlever dans la colonne gauche. Ce n'est pas une action qu'on effectue souvent et elle n'est pas liée à la colonne de gauche puisque sauf erreur ça permet de rafraichir les clés dans la page de la colonne gauche. 

![capture d ecran 2015-02-13 a 07 49 54](https://cloud.githubusercontent.com/assets/1556490/6183410/44499778-b355-11e4-9d56-79756f08772f.png)

Si c'est juste pour rafraichir la liste des clés, le bouton devrait même être à côté de la liste des clé. Mais pas passer trop de temps sur ce point car sera corrigé dans nouvelle version.

**Comment by CiGit** [comment]
Je n'ai pas du tout cette interface ...
