### ISSUE TITLE
Lobby: search scénario, partie n'est plus visible

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#929]
Idem dans l'éditeur de scénario.
on voit la loupe, mais plus le champ pour introduire le texte de la recherche.

![capture d ecran 2015-02-15 a 19 33 55](https://cloud.githubusercontent.com/assets/1556490/6204390/b7eb10b2-b549-11e4-9b29-84f77b12e5f1.png)

Si je clique sur la loupe, le champ de saisie apparait.

**Comment by CiGit** [comment]
Oui c'était un test, réduire la taille (surtout pour l'éditeur qui en avait besoin).
Vraisemblablement un échec ...

**Comment by djaccard** [comment]
bonne idée de tester des variantes ! mais alors, je l'ai vu comme un bug...
surtout qu'il se refermait après avoir lancé la recherche => tu ne sais plus sur quoi est actuellement la recherche.
