### ISSUE TITLE
PMG rés. automatique -  cohérence tâches, gantt, gatt ressource

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#936]
A voir si toujours nécessaire après discussion sur issue 935.

Pas cohérente entre les 3 onglets:
- gantt tâches: tâche 5 planifiée aux périodes 6, 7
- gantt ressource: on affecte tâche 5 à Luc )=> le réserve pour période 8
- onglet tâches: luc affiché en gras, comme s'il allait débuter à travailler période 5 (période en cours)

Je laisse la partie dans l'état.

![capture d ecran 2015-02-16 a 13 36 45](https://cloud.githubusercontent.com/assets/1556490/6212063/4cfe1b58-b5e1-11e4-803a-0211e3a9fbcc.png)

![capture d ecran 2015-02-16 a 13 36 57](https://cloud.githubusercontent.com/assets/1556490/6212064/4fdf76fa-b5e1-11e4-8e63-992576d77466.png)

![capture d ecran 2015-02-16 a 13 36 35](https://cloud.githubusercontent.com/assets/1556490/6212065/53bdbc50-b5e1-11e4-8b81-9bf048a9fa2f.png)

**Comment by maxencelaurent** [comment]
Pour qu'une ressource soit en gras, il faut que :
1) la ressources ne soit pas indisponible (ni en rouge, ni avec le délai d'engagement (tiens, il faudra regarder comment ça se comporte lorsque le délai d'engagement n'est plus pris en compte lorsqu'on dépasse le nombre de période prévu...))
2) Qu'une tâche lui soit affectée
