### ISSUE TITLE
clé pas visible

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#939]
toujours ce problème de clé pas visible pour le trainer.
Navigateur: chrome, mac

![capture d ecran 2015-02-25 a 08 51 11](https://cloud.githubusercontent.com/assets/1556490/6366810/92eba572-bccb-11e4-9f9d-7fc3c411d4f0.png)

**Comment by maxencelaurent** [comment]
est-ce que avec Firefox ou autre sous mac, y a aussi le même problème ?

**Comment by djaccard** [comment]
sur firefox: on voit 2 lettres de plus, mais ensuite, même problème
sur safari: on voit 2 lettres de plus, mais ensuite, même problème

**Comment by Rapou** [comment]
Les styles pour tout le système de conteneurs de l'option 1 est édité pour être plus cohérent (pas de débordement des conteneurs, positionnements relatifs).
Il y avait aussi un paramètre size="12" qui a été enlevé. Il empêchait sous chrome d'avoir une largeur automatique.
OK sur Chrome, Firefox et Safari (La largeur auto crée des espaces différents entre les navigateurs après la clé.)
