### ISSUE TITLE
Autoréservation Resources: on peut cliquer dans le calendrier

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#940]
sur calendrier, pointeur en main => on clique (par exemple semaine 2) => ça réserve la semaine (case en bleu) puis disparait (case de nouveau en blanc) et ressource passe avec le truc rouge à gauche.

![capture d ecran 2015-02-25 a 08 53 45](https://cloud.githubusercontent.com/assets/1556490/6366858/252f9f24-bccc-11e4-9fda-dd995274e5be.png)

**Comment by maxencelaurent** [comment]
t'est pas en vacance toi ? :-P

**Comment by djaccard** [comment]
je passe juste quelques heures à la maison ;-) 
rassure-toi, on repart bientôt pour la cabane dans le jura, sans ordi

**Comment by maxencelaurent** [comment]
ok c'était un grosse stupidité de ma part. C'est le même problème que #942  et #941

**Comment by djaccard** [comment]
j'ai pensé (que c'était le m problème, pas grosse stupidité)
