### ISSUE TITLE
CEP game: variable current phase not found

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#952]
Je l'ai déplacée dans un dossier (elle était avant à la racine)
=> plante quand je clique sur next period

![capture d ecran 2015-03-13 a 07 57 42](https://cloud.githubusercontent.com/assets/1556490/6634329/c583fd1c-c956-11e4-9d24-bfa945b8d4e2.png)

en attendant, je l'ai remise à la racine.

**Comment by maxencelaurent** [comment]
copy of #953
