### ISSUE TITLE
CEP game: humanResources not defined

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#953]
urgent car Pierre Jacot va travailler dessus d'ici un moment. 

plante à l'avancement de période.

J'ai fait de l'ordre dans les variables et dossiers. Peut-être déplacé quelque chose qui était à la racine, mais je ne sais pas laquelle.

Il ne devrait pas y avoir dans les jeux des variables liées à la racine et qui font planter quand on les met dans un dossier.

![capture d ecran 2015-03-13 a 07 57 42](https://cloud.githubusercontent.com/assets/1556490/6634349/55bbb10e-c957-11e4-8c85-891b4f705cec.png)

**Comment by djaccard** [comment]
en allant regarder le server script, j'ai supposé que ça correspondait aux cartes temps (drôle de script alias) => j'ai remis en attendant les cartes temps à la racine et ça fonctionne pour Pierre.
On attend la correction remttre les cartes temps dans le dossier "variable jeu"

**Comment by maxencelaurent** [comment]
ok c'est corrigé, j'ai mis les deux variables concernées dans le dossier "Variables Jeu" (Scénario CEP 2015 uniqument)
