### ISSUE TITLE
treeview: dossiers copiés

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#958]
truc très bizarre.
je crée un dossier "processus", dans le dossier "trigger"
![capture d ecran 2015-03-15 a 10 20 49](https://cloud.githubusercontent.com/assets/1556490/6655357/426acdf4-cafd-11e4-8e63-8d65b3fbe371.png)
le dossier est nommé (2) alors qu'il n'y en à qu'un.

Ensuite, j'y ajoute des varaibles et tout à coups, lors de l'ajout d'une variable, le dossier processus est copié en bas du treeview.
![capture d ecran 2015-03-15 a 10 21 48](https://cloud.githubusercontent.com/assets/1556490/6655358/679cc05a-cafd-11e4-8ee5-99e41697a8f2.png)

**Comment by Rapou** [comment]
Par rapport à la démo que tu m'as faite ce matin, le problème de copie de dossier doit être corrigé avec le fix de #903. 
J'ai fait plusieurs essais depuis et je n'ai plus le problème.
