### ISSUE TITLE
treeview: copy => mettre nouvel élément dans le même dossier (cj: 2j yc #958, #895 et package)

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#960]
On devrait retrouver le nouvel élément en dessous de celui qu'on vient de copier. Ici, je viens de copier AP1-A030 
![capture d ecran 2015-03-16 a 13 23 02](https://cloud.githubusercontent.com/assets/1556490/6665940/bd1a50d2-cbdf-11e4-9240-15d0f49acbe1.png)
desactivate periode 2 si effectuée

**Comment by djaccard** [comment]
en fait, j'ai vu ensuite que si je rafraichi la page, il sont dans le même dossier.

**Comment by Rapou** [comment]
Même que pour #958

**Comment by CiGit** [comment]
link #958, #895
