### ISSUE TITLE
PMG: delayed impact: inversion add et set

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#968]
Dans le wysiwyg, on a add to bonus ratio (dernière ligne):
![capture d ecran 2015-03-30 a 11 19 28](https://cloud.githubusercontent.com/assets/1556490/6893647/e0b8a3fa-d6ce-11e4-9fc1-1b5ff5647060.png)

Mais le code généré est Set bonus ratio:
![capture d ecran 2015-03-30 a 11 20 29](https://cloud.githubusercontent.com/assets/1556490/6893650/e288f324-d6ce-11e4-8fe1-17bc5e2352a1.png)

Des étudiants à equey étaient bloqués. J'ai corrigé leur bonus ratio à 1, mais pas touché le code. 
La correction doit être faite pour  tous les scénarios et parties en cours.

**Comment by maxencelaurent** [comment]
Je regarde ça des que je rentre à la maison, ça sera fait ce soir

**Comment by maxencelaurent** [comment]
Ok, corrigé dans tout les scénarios et parties ou j'ai trouvé le problèmes, c'est à dire: Artos, DemoGame et H&M.
