### ISSUE TITLE
BAC - EVM: mise à jour EVM

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#969]
Une participante à Equey a eu deux problèmes (liés?):
- elle dit qu'elle a entré toutes les valeurs des BAC et q'en quittant la page et revenant, seuls les BAC des deux premières tâches ont été sauvés (je n'ai pas vu si c'est vrai...)
- elle entre les BAC, puis va dans l'onglet EVM: la courbe n'est pas mise à jour. => revient voir les BAC (qui sont ien sauvés) => revient à EVM et cette fois la courbe est mise à jour (je l'ai vu => c'est vrai)

partie: artos22-7, étudiante: Ariunaa
navigateur: IE 11

**Comment by maxencelaurent** [comment]
Pour le moment, la meilleur solution est de prévenir l'utilisateur que des requêtes sont encore en cours s'il essaye de fermer sa page... On verra si on trouve mieux.

Je laisse l'issue ouverte
