### ISSUE TITLE
Admin: players des parties

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#970]
Ne pas afficher ni compter le player Guest.
On le voit dans le "view" et il est compté dans le nombre de players à facturer

![capture d ecran 2015-04-01 a 14 34 09](https://cloud.githubusercontent.com/assets/1556490/6941036/463cb9a6-d87c-11e4-92a0-3f1bb975f845.png)

**Comment by djaccard** [comment]
on dirait que pas pour toutes les parties la même chose (PM game: on ne voit pas le guest player)

**Comment by CiGit** [comment]
N'y a-t-il pas de confusion entre _guest_ et _test player_ ?

**Comment by djaccard** [comment]
disparaitra avec nouvelle version (plus de login as guest)
