### ISSUE TITLE
PMG: mise en forme Gantt suivi

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#973]
Passé:
- la baseline devrait rester en grisé (au liue de devenir bleu clair)
- la couleur du worked dans la légende ne correspond pas à celle sur le Gantt (prendre celle de la légende)

![capture d ecran 2015-04-29 a 12 00 04](https://cloud.githubusercontent.com/assets/1556490/7388670/4a06208a-ee67-11e4-90da-5fe92bbc1575.png)

**Comment by maxencelaurent** [comment]
J'en ai profité pour que les deux GANTT se ressemble plus.

Pour les resources: 
![image](https://cloud.githubusercontent.com/assets/6583528/7409903/7ac82c4a-ef2a-11e4-89ae-80a29ca41e59.png)
![image](https://cloud.githubusercontent.com/assets/6583528/7409924/ab222ada-ef2a-11e4-954c-755b463f0540.png)
Pour les tâches:
![image](https://cloud.githubusercontent.com/assets/6583528/7409908/8748290c-ef2a-11e4-94e8-2ab466f90180.png)
![image](https://cloud.githubusercontent.com/assets/6583528/7409918/97a6e68a-ef2a-11e4-82e6-591159f2e3a4.png)

**Comment by djaccard** [comment]
cool !
