### ISSUE TITLE
PMG Message pas assez de cartes temps

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#974]
Est-ce qu'on peut imaginer un message plus clair ?

![capture d ecran 2015-04-29 a 12 06 08](https://cloud.githubusercontent.com/assets/1556490/7388772/3616b3ea-ee68-11e4-9dca-c64417d9685e.png)

**Comment by maxencelaurent** [comment]
C'est pourtant clair, non ?

**Comment by maxencelaurent** [comment]
Voilà : 
![image](https://cloud.githubusercontent.com/assets/6583528/7410016/7570d75a-ef2b-11e4-9383-76921937d20a.png)

Par contre, j'attends une autre mise à jour pour mettre en ligne...

**Comment by djaccard** [comment]
pour moi c'était clair !
