### ISSUE TITLE
Changement tâches

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#975]
Partie: http://wegas.albasim.ch/game-play.html?gameId=1155285

Freyssard envoi mail fin de tâche le 7 avril
![capture d ecran 2015-04-29 a 14 30 17](https://cloud.githubusercontent.com/assets/1556490/7390874/58e0297e-ee7c-11e4-9aa6-487e490c8eca.png)

Freyssard ne passe pas à la tâche suivante de sa liste (30), qui était pourtant possible de réaliser:
![capture d ecran 2015-04-29 a 14 31 28](https://cloud.githubusercontent.com/assets/1556490/7390884/7d54a87a-ee7c-11e4-845b-14dddd44feee.png)

Je laisse la partie dans l'état

**Comment by maxencelaurent** [comment]
pas compris...

Quand on regarde le gannt de freyssart, on voit à la periode 4 (=mois d'avril) qu'il(s) a(ont) travaillé sur les tâches 10 et 30. C'est d'ailleurs ce qu'indique le message : 
> Bonjour, 
> 
> La tâche "Système production froid climatisation" est terminée. 
> 
> ***Depuis le 7 avril, je travaille sur la tâche "Ventilation: moteur ventilateur".***
> 
> Salutations 
> Freyssart SA
> Chauffage, ventilation, climatisation


En plus, la tâche 30 est réalisée à 26%

**Comment by maxencelaurent** [comment]
Par contre, je me dis qu'on pourrait ajouter les numéros de tâches dans les mails

**Comment by djaccard** [comment]
oui, ce serait cool d'avoir les no des tâches dans les mails.
Pour le reste, c'est moi qui ai dû avoir les yeux qui se croisent ;-((
