### ISSUE TITLE
PMG: error add number at instance property

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#976]
![capture d ecran 2015-04-30 a 16 33 47](https://cloud.githubusercontent.com/assets/1556490/7415048/c50e9f38-ef56-11e4-81a4-4b7a2d0fce67.png)

**Comment by maxencelaurent** [comment]
ok, c'était la question R-C010, refuser qui avait un delayed_impact sur un tâche non spécifiée...

**Comment by maxencelaurent** [comment]
c'est corrigé dans le scénario, pas dans les parties
