### ISSUE TITLE
PMG: add assignement to resource

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#977]
le bouton add a disparu (il est encore en fonction si on vient avec la souris au bon endroit, mais moins intuitif ;-)
![capture d ecran 2015-05-01 a 11 55 56](https://cloud.githubusercontent.com/assets/1556490/7428946/24d43688-eff9-11e4-9c2e-d469e24f96a3.png)

**Comment by maxencelaurent** [comment]
Pas chez moi:
![image](https://cloud.githubusercontent.com/assets/6583528/7429019/65e57b5e-effa-11e4-87c7-809d0e53feed.png)

T'as quel navigateur ?
