### ISSUE TITLE
problème login sur firefox windows

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#988]
firefox 38.01, windows
on n'arrive pas créer un compte ou se loger. ça fait un message "danger" en vert.
Cyril: probablement dû au mot de passe pas encrypté

**Comment by djaccard** [comment]
Cyril: probablement dû au mot de passe pas encrypté
=> atttendre mise en oeuvre ssl par cyril

**Comment by CiGit** [comment]
Firefox version
- 38.0.1
- 43.0.1
- 44.0.2
- 46.0a2

Pas de reproduction
