### ISSUE TITLE
co-scenarist: share

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#996]
quelle est le rôle du bouton share ?
on ajoute un scénariste en entrant son nom puis choisir dans options proposées.
ensuite on lui donne les droits, mais on n'utilise pas le bouton share.
![capture d ecran 2015-06-03 a 12 18 18](https://cloud.githubusercontent.com/assets/1556490/7957864/c3707ca6-09ea-11e5-8ca1-9e8392da421e.png)

**Comment by Rapou** [comment]
Bouton et label enlevé + placeholder remplacé par "share with user"
