### ISSUE TITLE
palyer: leave team

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#998]
je n'arrive pas à quitter "test eval3" (domplayer)

![capture d ecran 2015-06-08 a 16 02 48](https://cloud.githubusercontent.com/assets/1556490/8036414/f1a5b990-0df7-11e5-88a8-d4c847604b62.png)

**Comment by djaccard** [comment]
semble lié aux scénarios avec évaluations croisées. 
parfois on peut quitter, parfois pas. Est-ce dû a si on commencer l'évaluation croisée ?

**Comment by maxencelaurent** [comment]
j’imagine qu'il manque une suppression en cascade lorsque les eval sont déjà dispatchées. 
ça devrait pas être compliqué
