### ISSUE TITLE
Création nouveau player => on voit l'ancien

### ISSUE THREAD

**Issue by djaccard** [Heigvd/Wegas#999]
j'ai créé le player domplayer1 => je me connecte et vois les jeux de l'ancien joueur connecté sur ce navigateur (domplayer):
![capture d ecran 2015-06-08 a 16 07 08](https://cloud.githubusercontent.com/assets/1556490/8036523/a24c5c40-0df8-11e5-890c-787b5427ad57.png)

Je rafraichi la page=> plus rien:
![capture d ecran 2015-06-08 a 16 07 20](https://cloud.githubusercontent.com/assets/1556490/8036516/9dc229a2-0df8-11e5-8c64-074e0ca7db51.png)

**Comment by Rapou** [comment]
Corrigé
